<?php
namespace App\Services;
use RuntimeException;use Symfony\Component\Process\Process;
class AllowedSparkRunner{
 private const COMMANDS=['list'=>[],'migrate:status'=>[],'key:generate'=>['--force'],'cache:clear'=>[],'logs:clear'=>['--force'],'migrate'=>[],'ikontrol:database-check'=>[],'ikontrol:stamps-status'=>[],'ikontrol:logging-status'=>[],'ikontrol:log-check'=>[]];
 public function run(string$p,string$c,array$a=[]):array{if(!array_key_exists($c,self::COMMANDS)||$a!==self::COMMANDS[$c])throw new RuntimeException('Comando Spark no permitido.');return$this->execute($p,$c,$a,null,in_array($c,['list','migrate:status'],true)?20000:4000);}
 public function runWithInput(string$p,string$c,array$a,string$input):array{if(!in_array($c,['ikontrol:admin-provision','ikontrol:admin-password-set'],true))throw new RuntimeException('Comando Spark sensible no permitido.');if(($c==='ikontrol:admin-provision'&&count($a)!==2)||($c==='ikontrol:admin-password-set'&&count($a)!==1))throw new RuntimeException('Argumentos de comando no permitidos.');foreach($a as$v)if(!is_string($v)||str_contains($v,"\0")||str_contains($v,"\n"))throw new RuntimeException('Argumento de comando no permitido.');return$this->execute($p,$c,$a,$input.PHP_EOL,4000,[$input]);}
 public function runStampMovement(string$p,string$action,int$q,string$reason,string$id):array{if(!in_array($action,['credit','debit'],true)||$q<1||$q>1000000||!preg_match('/\A[a-f0-9]{32}\z/',$id))throw new RuntimeException('Movimiento de timbres inválido.');$reason=trim($reason);if($reason===''||mb_strlen($reason)>500||str_contains($reason,"\0")||preg_match('/[\r\n]/',$reason))throw new RuntimeException('Motivo inválido.');return$this->execute($p,'ikontrol:stamps-adjust',[$action,(string)$q,$id,$reason],null,20000);}
 public function runDiagnostic(string$p,string$c,string$email):array{if(!in_array($c,['ikontrol:admin-diagnose','ikontrol:dashboard-check'],true)||!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($email)>255)throw new RuntimeException('Diagnóstico o correo no permitido.');return$this->execute($p,$c,[strtolower($email)],null,20000);}
 private function execute(string$p,string$c,array$a,?string$input=null,int$limit=4000,array$extra=[]):array{$root=realpath((string)config('ikontrol.instances_root'));$cwd=realpath($p);if($root===false||$cwd===false||!str_starts_with($cwd,$root.DIRECTORY_SEPARATOR)||is_link($cwd))throw new RuntimeException('El directorio de ejecución no es seguro.');$binary=(string)config('ikontrol.deployment.php_binary',PHP_BINARY);if($binary===''||str_contains($binary,"\0")||str_contains($binary,"\n"))throw new RuntimeException('El binario PHP configurado no es válido.');$started=microtime(true);$process=new Process(array_merge([$binary,'spark',$c],$a),$cwd,['CI_ENVIRONMENT'=>'production']);if($input!==null)$process->setInput($input);$process->setTimeout((int)config('ikontrol.deployment.command_timeout',300));$process->run();$stdout=$this->redact($process->getOutput(),$extra);$stderr=$this->redact($process->getErrorOutput(),$extra);return['exit_code'=>$process->getExitCode(),'duration_ms'=>(int)((microtime(true)-$started)*1000),'output'=>mb_substr(trim($stdout!==''?$stdout:$stderr),0,$limit),'stdout'=>mb_substr(trim($stdout),0,$limit),'stderr'=>mb_substr(trim($stderr),0,$limit),'stdout_tail'=>mb_substr(trim($stdout),-$limit),'stderr_tail'=>mb_substr(trim($stderr),-$limit),'cwd'=>$cwd,'php_binary'=>$binary];}
 private function redact(string$v,array$extra=[]):string{foreach(array_merge($extra,[(string)config('ikontrol.db.password'),(string)config('ikontrol.cpanel.token')])as$s)if($s!=='')$v=str_replace($s,'[REDACTED]',$v);return preg_replace(['/(password|token|secret|authorization)\s*[=:]\s*[^\s,;]+/i','/bearer\s+[^\s]+/i'],['$1=[REDACTED]','Bearer [REDACTED]'],$v)??'';}
}
