<?php
namespace App\Services;
use App\Exceptions\CpanelException; use Illuminate\Http\Client\{ConnectionException,PendingRequest,RequestException}; use Illuminate\Support\Facades\{Http,Log}; use Throwable;
class CpanelService {
 private const TIMEOUT_SECONDS=20;
 private function configuration():array{return config('ikontrol.cpanel');}
 public function isConfigured():bool{$c=$this->configuration();return filled($c['host'])&&filled($c['username'])&&filled($c['token']);}
 private function client():PendingRequest{if(!$this->isConfigured())throw new CpanelException('cPanel configuration incomplete.','cPanel no está configurado.',['status'=>'NOT_CONFIGURED']);$c=$this->configuration();return Http::acceptJson()->timeout(self::TIMEOUT_SECONDS)->connectTimeout(10)->withHeaders(['Authorization'=>'cpanel '.$c['username'].':'.$c['token']]);}
 private function endpoint(string $module,string $function):string{$c=$this->configuration();$configured=trim((string)$c['host']);$parts=parse_url(str_contains($configured,'://')?$configured:'https://'.$configured);$host=$parts['host']??'';$port=$parts['port']??$c['port'];if($host==='')throw new CpanelException('Invalid cPanel host.','El host de cPanel no es válido.',['status'=>'NOT_CONFIGURED']);return sprintf('https://%s:%d/execute/%s/%s',$host,$port,$module,$function);}
 private function call(string $module,string $function,array $parameters=[]):array{$operation=$module.'/'.$function;$started=microtime(true);try{$response=$this->client()->get($this->endpoint($module,$function),$parameters);$payload=$response->json();if(!$response->successful()||!is_array($payload)||(int)($payload['status']??0)!==1){$message=$this->extractMessage($payload);$this->logFailure($operation,$response->status(),$message,null,$started);throw new CpanelException('cPanel rejected '.$operation,$this->safeUiMessage($response->status(),$message),['status'=>'ERROR','http_status'=>$response->status(),'operation'=>$operation]);}return $payload;}catch(CpanelException $e){throw $e;}catch(ConnectionException $e){$type=$this->connectionErrorType($e->getMessage());$this->logFailure($operation,null,null,$type,$started);throw new CpanelException('cPanel connection failed.',$type==='TIMEOUT'?'cPanel no respondió dentro del tiempo permitido.':($type==='SSL_ERROR'?'No fue posible validar la conexión SSL con cPanel.':'No fue posible conectar con el host de cPanel.'),['status'=>'ERROR','error_type'=>$type,'operation'=>$operation]);}catch(RequestException $e){$status=$e->response?->status();$message=$this->extractMessage($e->response?->json());$this->logFailure($operation,$status,$message,'HTTP_ERROR',$started);throw new CpanelException('cPanel HTTP request failed.',$this->safeUiMessage($status,$message),['status'=>'ERROR','http_status'=>$status,'operation'=>$operation]);}catch(Throwable $e){$this->logFailure($operation,null,null,class_basename($e),$started);throw new CpanelException('Unexpected cPanel error.','Ocurrió un error inesperado al consultar cPanel.',['status'=>'ERROR','operation'=>$operation]);}}
 public function testConnection():array{$databases=$this->listDatabases();return ['success'=>true,'status'=>'CONNECTED','message'=>'Conexión con cPanel correcta; se consultaron las bases existentes.','database_count'=>count($databases)];}
 public function listDatabases():array{$response=$this->call('Mysql','list_databases');return collect($response['data']??[])->map(fn($db)=>is_array($db)?($db['database']??$db['name']??null):(is_string($db)?$db:null))->filter()->values()->all();}
 public function createDatabase(string $name):array{return $this->call('Mysql','create_database',['name'=>$name]);}
 public function assignUserToDatabase(string $database):array{return $this->call('Mysql','set_privileges_on_database',['user'=>config('ikontrol.db.username'),'database'=>$database,'privileges'=>'ALL PRIVILEGES']);}
 public function databaseExists(string $name):bool{return in_array($name,$this->listDatabases(),true);}
 private function extractMessage(mixed $payload):?string{if(!is_array($payload))return null;$message=$payload['errors'][0]??$payload['messages'][0]??$payload['message']??null;return is_scalar($message)?$this->sanitize((string)$message):null;}
 private function sanitize(string $message):string{$token=(string)config('ikontrol.cpanel.token');if($token!=='')$message=str_replace($token,'[REDACTED]',$message);$message=preg_replace('/Authorization\s*:\s*[^\s,]+/i','Authorization: [REDACTED]',$message);return mb_substr(trim(strip_tags($message)),0,500);}
 private function safeUiMessage(?int $status,?string $message):string{$prefix=$status?"cPanel respondió HTTP {$status}.":'cPanel rechazó la solicitud.';return $message?$prefix.' '.$message:$prefix.' Revise host, usuario, token y permisos UAPI.';}
 private function connectionErrorType(string $message):string{$m=strtolower($message);return str_contains($m,'timed out')||str_contains($m,'timeout')?'TIMEOUT':(str_contains($m,'ssl')||str_contains($m,'certificate')?'SSL_ERROR':'CONNECTION_ERROR');}
 private function logFailure(string $operation,?int $status,?string $message,?string $type,float $started):void{Log::warning('cPanel UAPI request failed.',['operation'=>$operation,'http_status'=>$status,'cpanel_message'=>$message?$this->sanitize($message):null,'error_type'=>$type,'timeout_seconds'=>self::TIMEOUT_SECONDS,'elapsed_ms'=>(int)((microtime(true)-$started)*1000)]);}
}
