<?php
namespace App\Services;
use App\Models\IkontrolInstance; use Illuminate\Support\Facades\DB; use Throwable;
class IkontrolInstanceConnectionService {
 public function testGlobalConnection():array{if(!$this->globalConfigurationIsComplete())return ['success'=>false,'status'=>'NOT_CONFIGURED','message'=>'La conexión MySQL global no está configurada.','response_time_ms'=>0];return $this->attempt('ikontrol_global_connection','information_schema');}
 public function test(IkontrolInstance $instance):array{$result=$this->attempt('instance_'.$instance->id,$instance->db_name);$instance->update(['last_connection_at'=>now(),'last_connection_status'=>$result['success']?'CONNECTED':'ERROR','last_connection_error'=>$result['success']?null:$result['message']]);return $result;}
 private function globalConfigurationIsComplete():bool{return filled(config('ikontrol.db.host'))&&filled(config('ikontrol.db.port'))&&filled(config('ikontrol.db.username'))&&config('ikontrol.db.password')!==null;}
 private function attempt(string $connection,string $database):array{config(["database.connections.$connection"=>['driver'=>'mysql','host'=>config('ikontrol.db.host'),'port'=>config('ikontrol.db.port'),'database'=>$database,'username'=>config('ikontrol.db.username'),'password'=>config('ikontrol.db.password'),'charset'=>'utf8mb4','collation'=>'utf8mb4_unicode_ci','prefix'=>'','strict'=>true,'options'=>extension_loaded('pdo_mysql')?array_filter([\PDO::ATTR_TIMEOUT=>10]):[]]]);$started=microtime(true);try{DB::purge($connection);DB::connection($connection)->select('SELECT 1');return ['success'=>true,'status'=>'CONNECTED','message'=>'Conexión MySQL correcta.','response_time_ms'=>(int)((microtime(true)-$started)*1000)];}catch(Throwable){return ['success'=>false,'status'=>'ERROR','message'=>'No fue posible conectar con MySQL. Revise host, puerto, usuario, password y permisos.','response_time_ms'=>(int)((microtime(true)-$started)*1000)];}finally{DB::disconnect($connection);}}
}
