<?php
namespace App\Services;
use App\Models\{IkontrolInstance,InstanceInstallationLog};use Illuminate\Http\Client\ConnectionException;use Illuminate\Support\Facades\Http;use RuntimeException;
class IkontrolInstanceOperationsService{
 public function __construct(private IkontrolDeploymentService$d,private IkontrolInstanceConnectionService$c,private CpanelService$cp,private AuditService$a,private InstanceFilesystemService$fs,private InstanceProvisioningService$p){}
 public function verifyFiles(IkontrolInstance$i):array{$path=$this->path($i);$checks=[];foreach(['index.php','spark','app','system','.env','writable']as$x)$checks[$x]=file_exists($path.DIRECTORY_SEPARATOR.$x);$status=!in_array(false,$checks,true)?'READY':($checks['index.php']&&$checks['spark']?'WARNING':'FAILED');return$this->finish($i,'verify_instance_files',$status,$checks);}
 public function verifyDatabase(IkontrolInstance$i):array{$admin=$this->c->test($i);$this->d->installOperationalCommandsFor($i);$app=$this->command($i,'ikontrol:database-check');return$this->finish($i,'verify_instance_database',$admin['success']&&$app['success']?'READY':'FAILED',['admin'=>$admin['status'],'application'=>$app['status']]);}
 public function reassignDatabaseUser(IkontrolInstance$i):array{$this->assertDatabase($i);$before=$this->c->test($i);$this->cp->assignUserToDatabase($i->db_name);$after=$this->c->test($i);if(!$after['success'])throw new RuntimeException('El usuario fue reasignado, pero la verificación MySQL continúa fallando.');$this->finish($i,'reassign_instance_database_user','SUCCESS');return['action'=>'REASSIGN_DATABASE_USER','before_status'=>$before['success']?'READY':'FAILED','action_result'=>'CPANEL_ASSIGNMENT_OK','verification_result'=>'MYSQL_CONNECTION_OK','after_status'=>'READY'];}
 public function key(IkontrolInstance$i):array{if(!$this->d->templateHasEncryptionKey($i)){$r=$this->d->runTemplateCommand($i,'key:generate',['--force']);if(($r['exit_code']??1)!==0)throw new RuntimeException('No fue posible generar encryption key.');}return$this->finish($i,'verify_instance_encryption_key','SUCCESS');}
 public function clearCache(IkontrolInstance$i):array{return$this->finishCommand($i,'clear_instance_cache','cache:clear');}
 public function migrate(IkontrolInstance$i):array{return$this->finishCommand($i,'migrate_instance','migrate');}
 public function provisionAdmin(IkontrolInstance$i,string$n,string$e,string$pw):array{$action=$this->sensitive($i,'create_instance_admin','ikontrol:admin-provision',[$n,$e],$pw);$protocol=app(ManagedCommandJsonProtocol::class);$admin=$protocol->decodeProcess($this->d->runInstalledDiagnosticCommand($i,'ikontrol:admin-diagnose',strtolower($e)));if(($admin['status']??null)!=='READY')throw new RuntimeException('Administrador creado o reparado, pero ADMIN_DIAGNOSE falló: '.($admin['reason']??'UNKNOWN_FAILURE').'.');$dashboard=$protocol->decodeProcess($this->d->runInstalledDiagnosticCommand($i,'ikontrol:dashboard-check',strtolower($e)));if(($dashboard['status']??null)!=='READY')throw new RuntimeException('Administrador READY, pero DASHBOARD_CHECK falló: '.($dashboard['reason']??'UNKNOWN_FAILURE').'.');return['action'=>'CREATE_OR_REPAIR_INITIAL_ADMIN','before_status'=>'MISSING_OR_INCOMPLETE','action_result'=>$action['status'],'verification_result'=>'ADMIN_AND_DASHBOARD_READY','after_status'=>'READY'];}
 public function resetAdminPassword(IkontrolInstance$i,string$e,string$pw):array{return$this->sensitive($i,'reset_instance_admin_password','ikontrol:admin-password-set',[$e],$pw);}
 public function health(IkontrolInstance$i,?string$email=null):array{$files=$this->verifyFiles($i);$admin=$this->c->test($i);$this->d->installOperationalCommandsFor($i);$app=$this->command($i,'ikontrol:database-check');$http=$this->http($i);$infrastructure=$files['status']==='READY'&&$admin['success']?'HEALTHY':'FAILED';$application=$app['success']&&$http['healthy']?'HEALTHY':'FAILED';$adminStatus=$dashboardStatus='NOT_CHECKED';if($email){$diagnostics=app(InstanceRuntimeDiagnosticService::class);$adminStatus=$diagnostics->diagnoseAdmin($i,$email)['status'];$dashboardStatus=$diagnostics->diagnoseDashboard($i,$email)['status'];}$checks=['infrastructure'=>$infrastructure,'application'=>$application,'administrator'=>$adminStatus,'dashboard'=>$dashboardStatus,'files'=>$files['status'],'admin_database'=>$admin['status'],'application_database'=>$app['status'],'http'=>$http];$status=$infrastructure==='FAILED'?'FAILED':($application!=='HEALTHY'?'INFRASTRUCTURE_HEALTHY':($adminStatus==='READY'&&$dashboardStatus==='READY'?'AUTHENTICATED_READY':'APPLICATION_READY'));return$this->finish($i,'health_check_instance',$status,$checks);}
 public function restart(IkontrolInstance$i,string$confirmation):IkontrolInstance{$this->assertDestructive($i,$confirmation);$this->fs->removeManagedFolder($i->slug);if($this->cp->databaseExists($i->db_name))$this->cp->deleteDatabase($i->db_name);$this->a->record('restart_test_instance','Recursos de prueba eliminados antes de reprovisionar.',$i);return$this->p->reprovisionTestInstance($i);}
 public function delete(IkontrolInstance$i,string$confirmation,bool$folder,bool$database,bool$record):void{$this->assertDestructive($i,$confirmation);if(!$folder&&!$database&&!$record)throw new RuntimeException('Seleccione al menos un recurso.');if($folder)$this->fs->removeManagedFolder($i->slug);if($database&&$this->cp->databaseExists($i->db_name))$this->cp->deleteDatabase($i->db_name);$this->a->record('delete_test_instance','Eliminación controlada de recursos de prueba.',$i,['folder'=>$folder,'database'=>$database,'record'=>$record]);if($record)$i->delete();}
 private function http(IkontrolInstance$i):array{try{$r=Http::timeout(15)->connectTimeout(8)->withOptions(['allow_redirects'=>['max'=>5,'track_redirects'=>true]])->get('https://'.$i->slug.'.ikontrol.solutions');return['healthy'=>$r->successful(),'status'=>$r->status(),'final_url'=>$r->effectiveUri()?->__toString()];}catch(ConnectionException){return['healthy'=>false,'status'=>null,'error'=>'DNS_SSL_CONNECTION_ERROR'];}}
 private function finishCommand(IkontrolInstance$i,string$action,string$command):array{$r=$this->command($i,$command);if(!$r['success'])throw new RuntimeException('La operación CodeIgniter falló.');return$this->finish($i,$action,'SUCCESS',['duration_ms'=>$r['duration_ms']]);}
 private function command(IkontrolInstance$i,string$command):array{$r=$this->d->runTemplateCommand($i,$command,[]);return['success'=>($r['exit_code']??1)===0,'status'=>($r['exit_code']??1)===0?'CONNECTED':'ERROR','duration_ms'=>$r['duration_ms']??0];}
 private function sensitive(IkontrolInstance$i,string$action,string$command,array$args,string$pw):array{if(strlen($pw)<12)throw new RuntimeException('La contraseña debe tener al menos 12 caracteres.');try{$r=$this->d->runSensitiveTemplateCommand($i,$command,$args,$pw);}finally{unset($pw);}if(($r['exit_code']??1)!==0)throw new RuntimeException('La operación administrativa de iKontrol falló.');return$this->finish($i,$action,'SUCCESS',['duration_ms'=>$r['duration_ms']??0]);}
 private function finish(IkontrolInstance$i,string$action,string$status,array$details=[]):array{$this->a->record($action,'Operación controlada ejecutada sobre la instalación.',$i,['status'=>$status]);InstanceInstallationLog::create(['instance_id'=>$i->id,'step'=>strtoupper($action),'status'=>in_array($status,['FAILED','ERROR'])?'FAILED':'SUCCESS','message'=>'Resultado: '.$status.'.','created_at'=>now()]);return['status'=>$status]+$details;}
 private function path(IkontrolInstance$i):string{$root=realpath((string)config('ikontrol.instances_root'));$path=realpath((string)$i->absolute_path);if($root===false||$path===false||is_link($path)||!str_starts_with($path,$root.DIRECTORY_SEPARATOR)||basename($path)!==$i->slug.config('ikontrol.folder_suffix'))throw new RuntimeException('La carpeta administrada no es segura o no existe.');return$path;}
 private function assertDatabase(IkontrolInstance$i):void{$prefix=(string)config('ikontrol.db.prefix');if($prefix===''||!str_starts_with($i->db_name,$prefix)||!preg_match('/\A[a-zA-Z0-9_]+\z/',$i->db_name))throw new RuntimeException('La base no pertenece al prefijo administrado.');}
 private function assertDestructive(IkontrolInstance$i,string$c):void{if(!$i->is_test||$i->installation_status->value==='READY'||strcasecmp($i->name,'DOLD')===0||strcasecmp($i->slug,'dold')===0)throw new RuntimeException('La instalación está protegida contra eliminación.');if(!hash_equals($i->slug,trim($c)))throw new RuntimeException('La confirmación no coincide con el slug.');$this->path($i);$this->assertDatabase($i);}
}
