<?php
namespace App\Services;
use App\Models\IkontrolInstance;use RuntimeException;
class InstanceLogService{
 private const LINES=[100,500,1000];private const BYTES=1048576;
 public function __construct(private AuditService$a,private IkontrolDeploymentService$d){}
 public function listing(IkontrolInstance$i):array{$dir=$this->directory($i);if(!is_dir($dir))return[];$files=[];foreach(new \DirectoryIterator($dir)as$f){if(!$f->isFile()||$f->isLink()||strtolower($f->getExtension())!=='log')continue;$files[]=['name'=>$f->getFilename(),'size'=>$f->getSize(),'modified_at'=>$f->getMTime()];}usort($files,fn($a,$b)=>$b['modified_at']<=>$a['modified_at']);return$files;}
 public function read(IkontrolInstance$i,string$name,int$lines=100,?string$search=null):array{if(!in_array($lines,self::LINES,true)||!preg_match('/\A[A-Za-z0-9._-]+\.log\z/',$name))throw new RuntimeException('Archivo o límite de lectura inválido.');$dir=$this->directory($i);$path=$dir.DIRECTORY_SEPARATOR.$name;$real=realpath($path);$base=realpath($dir);if($real===false||$base===false||!str_starts_with($real,$base.DIRECTORY_SEPARATOR)||is_link($real)||!is_file($real))throw new RuntimeException('El archivo de log no existe o no es seguro.');$size=filesize($real);$handle=fopen($real,'rb');if(!$handle)throw new RuntimeException('No fue posible leer el log.');$read=min((int)$size,self::BYTES);if($read>0)fseek($handle,-$read,SEEK_END);$content=$read>0?(string)fread($handle,$read):'';fclose($handle);$rows=preg_split('/\R/',$content)?:[];$rows=array_slice($rows,-$lines);$search=trim((string)$search);if($search!==''){$needle=mb_substr($search,0,100);$rows=array_values(array_filter($rows,fn($row)=>mb_stripos($row,$needle)!==false));}$content=$this->redact(implode(PHP_EOL,$rows));return['name'=>$name,'size'=>$size,'modified_at'=>filemtime($real),'lines'=>$lines,'truncated'=>$size>self::BYTES,'content'=>$content];}
 public function recentErrors(IkontrolInstance$i):array{$errors=[];foreach(array_slice($this->listing($i),0,3)as$file){$data=$this->read($i,$file['name'],1000);foreach(preg_split('/\R/',$data['content'])?:[]as$line)if(preg_match('/\b(ERROR|CRITICAL|ALERT|EMERGENCY)\b/i',$line))$errors[]=mb_substr($line,0,500);}return array_slice($errors,-20);}
 public function clear(IkontrolInstance$i):void{$r=$this->d->runTemplateCommand($i,'logs:clear',['--force']);if(($r['exit_code']??1)!==0)throw new RuntimeException('No fue posible limpiar los logs.');$this->a->record('clear_instance_logs','Logs de la instancia limpiados mediante CodeIgniter.',$i);}
 private function directory(IkontrolInstance$i):string{$root=realpath((string)config('ikontrol.instances_root'));$instance=realpath((string)$i->absolute_path);if($root===false||$instance===false||is_link($instance)||!str_starts_with($instance,$root.DIRECTORY_SEPARATOR)||basename($instance)!==$i->slug.config('ikontrol.folder_suffix'))throw new RuntimeException('La ruta de la instancia no es segura.');return$instance.DIRECTORY_SEPARATOR.'writable'.DIRECTORY_SEPARATOR.'logs';}
 private function redact(string$s):string{foreach([(string)config('ikontrol.db.password'),(string)config('ikontrol.cpanel.token')]as$secret)if($secret!=='')$s=str_replace($secret,'[REDACTED]',$s);$patterns=['/(password|token|secret|DB_PASSWORD|IKONTROL_DB_PASSWORD|CPANEL_TOKEN)\s*[=:]\s*[^\s,;]+/i','$1=[REDACTED]','/authorization\s*:\s*[^\r\n]+/i','Authorization: [REDACTED]','/bearer\s+[A-Za-z0-9._~+\/-]+=*/i','Bearer [REDACTED]'];return preg_replace([$patterns[0],$patterns[2],$patterns[4]],[$patterns[1],$patterns[3],$patterns[5]],$s)??'';}
}
