<?php
namespace App\Services;
use App\Enums\InstallationStatus as S; use App\Models\{Client,IkontrolInstance,InstanceInstallationLog}; use Throwable;
class InstanceProvisioningService {
 public function __construct(private CpanelService $cpanel,private InstanceFilesystemService $fs,private IkontrolInstanceConnectionService $connection,private AuditService $audit){}
 public function databaseName(string $slug): string { if(!$this->fs->validateSlug($slug)) throw new \InvalidArgumentException('Slug invalido.'); $name=config('ikontrol.db.prefix').$slug; if(strlen($name)>64) throw new \InvalidArgumentException('El nombre de base excede 64 caracteres.'); return $name; }
 public function preview(string $slug): array{return ['folder_name'=>$this->fs->folderName($slug),'absolute_path'=>$this->fs->path($slug),'db_name'=>$this->databaseName($slug)];}
 public function preflight(string $slug): array { $p=$this->preview($slug); $checks=['slug_valid'=>$this->fs->validateSlug($slug),'folder_available'=>!$this->fs->folderExists($slug),'filesystem_writable'=>$this->fs->rootWritable(),'cpanel_available'=>false,'database_available'=>false]; try{$this->cpanel->testConnection();$checks['cpanel_available']=true;$checks['database_available']=!$this->cpanel->databaseExists($p['db_name']);}catch(Throwable){} return $p+['checks'=>$checks,'success'=>!in_array(false,$checks,true)]; }
 public function provision(array $data): IkontrolInstance { $client=!empty($data['client_id'])?Client::findOrFail($data['client_id']):Client::create(['name'=>$data['new_client_name'],'active'=>true]); $p=$this->preview($data['slug']); $i=IkontrolInstance::create(['client_id'=>$client->id,'name'=>$data['name'],'slug'=>$data['slug'],'folder_name'=>$p['folder_name'],'absolute_path'=>$p['absolute_path'],'db_host'=>config('ikontrol.db.host'),'db_port'=>config('ikontrol.db.port'),'db_name'=>$p['db_name'],'installation_status'=>S::Pending]); try{$this->step($i,S::Validating,function()use($data){if(!$this->preflight($data['slug'])['success'])throw new \RuntimeException('Preflight no superado.');});$this->step($i,S::CreatingFolder,fn()=>$this->fs->createFolder($i->slug));$this->step($i,S::CreatingDatabase,fn()=>$this->cpanel->createDatabase($i->db_name));$this->step($i,S::AssigningDatabaseUser,fn()=>$this->cpanel->assignUserToDatabase($i->db_name));$this->step($i,S::Registering,fn()=>true);$this->step($i,S::TestingConnection,function()use($i){$r=$this->connection->test($i);if(!$r['success'])throw new \RuntimeException($r['message']);return $r;});$i->update(['installation_status'=>S::ReadyForDeploy]);$this->log($i,S::ReadyForDeploy,'SUCCESS','Instalacion preparada para desplegar.');$this->audit->record('create_instance','Nueva instalacion preparada.',$i);}catch(Throwable $e){$failedStep=$i->installation_status;$i->update(['installation_status'=>S::Failed]);$this->log($i,$failedStep,'FAILED',$e->getMessage());report($e);}return $i->fresh(); }
 private function step(IkontrolInstance $i,S $status,callable $action): mixed{$i->update(['installation_status'=>$status]);$this->log($i,$status,'STARTED','Paso iniciado.');$r=$action();$this->log($i,$status,'SUCCESS','Paso completado.');return $r;}
 private function log(IkontrolInstance $i,S|string $step,string $status,string $message):void{InstanceInstallationLog::create(['instance_id'=>$i->id,'step'=>$step instanceof S?$step->value:$step,'status'=>$status,'message'=>mb_substr($message,0,2000),'created_at'=>now()]);}
}
