<?php
namespace App\Services;
use App\Enums\InstallationStatus as S; use App\Models\{Client,IkontrolInstance,InstanceInstallationLog}; use Throwable;
class InstanceProvisioningService {
 public function __construct(private CpanelService $cpanel,private InstanceFilesystemService $fs,private IkontrolInstanceConnectionService $connection,private AuditService $audit){}
 public function databaseName(string $slug):string{if(!$this->fs->validateSlug($slug))throw new \InvalidArgumentException('Slug inválido.');$name=config('ikontrol.db.prefix').$slug;if(strlen($name)>64)throw new \InvalidArgumentException('El nombre de base excede 64 caracteres.');return $name;}
 public function preview(string $slug):array{return ['folder_name'=>$this->fs->folderName($slug),'absolute_path'=>$this->fs->path($slug),'db_name'=>$this->databaseName($slug)];}
 public function preflight(string $slug):array{$preview=$this->preview($slug);$checks=['slug_valid'=>$this->fs->validateSlug($slug),'folder_available'=>!$this->fs->folderExists($slug),'filesystem_writable'=>$this->fs->rootWritable(),'cpanel_connected'=>false,'database_not_existing'=>false,'mysql_user_available'=>false];try{$databases=$this->cpanel->listDatabases();$checks['cpanel_connected']=true;$checks['database_not_existing']=!in_array($preview['db_name'],$databases,true);}catch(Throwable){}$checks['mysql_user_available']=$this->connection->testGlobalConnection()['success'];return $preview+['checks'=>$checks,'success'=>!in_array(false,$checks,true)];}
 public function provision(array $data):IkontrolInstance{$client=$data['client_mode']==='existing'?Client::findOrFail($data['client_id']):Client::create(['name'=>$data['new_client_name'],'active'=>true]);$preview=$this->preview($data['slug']);$instance=IkontrolInstance::create(['client_id'=>$client->id,'name'=>$data['name'],'slug'=>$data['slug'],'folder_name'=>$preview['folder_name'],'absolute_path'=>$preview['absolute_path'],'db_host'=>config('ikontrol.db.host'),'db_port'=>config('ikontrol.db.port'),'db_name'=>$preview['db_name'],'installation_status'=>S::Pending]);try{$this->step($instance,S::Validating,function()use($data){if(!$this->preflight($data['slug'])['success'])throw new \RuntimeException('Preflight no superado.');});$this->step($instance,S::CreatingFolder,fn()=>$this->fs->createFolder($instance->slug));$this->step($instance,S::CreatingDatabase,fn()=>$this->cpanel->createDatabase($instance->db_name));$this->step($instance,S::AssigningDatabaseUser,fn()=>$this->cpanel->assignUserToDatabase($instance->db_name));$this->step($instance,S::Registering,fn()=>true);$this->step($instance,S::TestingConnection,function()use($instance){$result=$this->connection->test($instance);if(!$result['success'])throw new \RuntimeException($result['message']);return $result;});$instance->update(['installation_status'=>S::ReadyForDeploy]);$this->log($instance,S::ReadyForDeploy,'SUCCESS','Instalación preparada para desplegar.');$this->audit->record('create_instance','Nueva instalación preparada.',$instance);}catch(Throwable $e){$failedStep=$instance->installation_status;$instance->update(['installation_status'=>S::Failed]);$this->log($instance,$failedStep,'FAILED',$e->getMessage());report($e);}return $instance->fresh();}
 private function step(IkontrolInstance $instance,S $status,callable $action):mixed{$instance->update(['installation_status'=>$status]);$this->log($instance,$status,'STARTED','Paso iniciado.');$result=$action();$this->log($instance,$status,'SUCCESS','Paso completado.');return $result;}
 private function log(IkontrolInstance $instance,S|string $step,string $status,string $message):void{InstanceInstallationLog::create(['instance_id'=>$instance->id,'step'=>$step instanceof S?$step->value:$step,'status'=>$status,'message'=>mb_substr($message,0,2000),'created_at'=>now()]);}
}
