<?php
namespace App\Services\LegacyFc2;
use App\Models\{FactucareConversionPlan,FactucareConversionPlanItem,IkontrolInstance};
use App\Services\IkontrolInstanceConnectionService;
use Illuminate\Database\Connection;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use RuntimeException;
class FactucareConversionPlannerService {
 public function __construct(private FactucareReaderService $reader,private IkontrolInstanceConnectionService $instances){}
 public function plan(int|string $legacyUserId,array $options=[]):array{$source=$this->reader->conversionSource((int)$legacyUserId);if(!($source['found']??false))throw new RuntimeException($source['message']??'Usuario FactuCare no disponible.');$options=$this->options($options);$catalog=$options['destination_instance_id']?$this->destination($options['destination_instance_id']):$this->emptyDestination();$dr=$this->duplicates($source['clients'],'rfc');$dp=$this->duplicates($source['products'],'code');$items=[$this->issuer($source,$catalog)];foreach($source['clients'] as $row)$items[]=$this->client($row,$options,$catalog,$dr);foreach($source['products'] as $row)$items[]=$this->product($row,$options,$catalog,$dp);$items[]=$this->csd($source['csd']??[]);foreach($source['folios'] as $row)$items[]=$this->series($row,$options,$catalog);$summary=$this->summary($source,$items,$dr,$dp);$status=$this->overallStatus($items,$catalog);return compact('source','options','catalog','items','summary','status')+['source_fingerprint'=>$this->fingerprint($source)];}
 public function persist(array $result,?FactucareConversionPlan $existing=null):FactucareConversionPlan{return DB::transaction(function()use($result,$existing){$plan=$existing??new FactucareConversionPlan();$plan->fill(['legacy_user_id'=>$result['source']['users_id'],'legacy_rfc'=>$result['source']['rfc'],'destination_instance_id'=>$result['options']['destination_instance_id'],'status'=>$result['status'],'options_json'=>$result['options'],'summary_json'=>$result['summary'],'source_fingerprint'=>$result['source_fingerprint'],'created_by'=>$existing?->created_by??auth()->id()])->save();if($existing)$plan->items()->delete();foreach($result['items'] as $item)FactucareConversionPlanItem::create($item+['plan_id'=>$plan->id]);return $plan->fresh(['items','destination']);});}
 public function sourceState(FactucareConversionPlan $plan):string{return hash_equals($plan->source_fingerprint,$this->plan($plan->legacy_user_id,$plan->options_json)['source_fingerprint'])?'SOURCE_UNCHANGED':'SOURCE_CHANGED';}
 private function options(array $i):array{return ['destination_instance_id'=>filled($i['destination_instance_id']??null)?(int)$i['destination_instance_id']:null,'default_cfdi_use'=>Str::upper($i['default_cfdi_use']??'G03'),'prepare_products'=>(bool)($i['prepare_products']??true),'default_tax_object'=>Str::upper($i['default_tax_object']??'02'),'default_tax'=>'IVA16','apply_default_tax'=>(bool)($i['apply_default_tax']??true),'force_default_tax'=>(bool)($i['force_default_tax']??false),'preserve_series'=>(bool)($i['preserve_series']??false)];}
 private function issuer(array $s,array $c):array{$p=$s['profile']??[];$w=[];if(!$this->validRfc($p['rfc']??''))$w[]='RFC emisor inválido o vacío.';if(!filled($p['legal_name']??null))$w[]='Falta razón social.';if(!preg_match('/^\d{5}$/',(string)($p['postal_code']??'')))$w[]='Falta código postal fiscal válido.';$reg=$this->lookup($c,'regimes',(string)($p['fiscal_regime']??''));if(!$reg['matched'])$w[]='Régimen SAT no encontrado en destino.';return $this->item('issuer','users_perfil',$s['users_id'],$w?'INCOMPLETE':'READY',$w?'REVIEW':'INSERT',['source'=>$p,'destination'=>['company'=>['name'=>$p['legal_name']??null,'vat_number'=>$p['rfc']??null,'address'=>$p['street']??null],'fiscal_profile'=>['profile_type'=>'issuer','legal_name'=>$p['legal_name']??null,'rfc'=>$p['rfc']??null,'tax_regime_code'=>$p['fiscal_regime']??null,'fiscal_postal_code'=>$p['postal_code']??null]],'lookups'=>['tax_regime'=>$reg]],$w);}
 private function client(array $r,array $o,array $c,array $dups):array{$w=[];$rfc=Str::upper(trim((string)($r['rfc']??'')));$invalid=!$this->validRfc($rfc);if($invalid)$w[]='RFC inválido o vacío.';if(isset($dups[$rfc]))$w[]='DUPLICATE_RFC';if(!filled($r['legal_name']??null))$w[]='Falta razón social.';if(!preg_match('/^\d{5}$/',(string)($r['postal_code']??'')))$w[]='Código postal fiscal ausente o inválido.';$reg=$this->lookup($c,'regimes',(string)($r['fiscal_regime']??''));if(!$reg['matched'])$w[]='Régimen fiscal no encontrado.';$use=$this->lookup($c,'cfdi_uses',$o['default_cfdi_use']);if($c['selected']&&!$use['matched'])$w[]='Uso CFDI default no existe en destino.';$exists=in_array($rfc,$c['client_rfcs'],true);$status=$invalid?'INVALID':($w?'REVIEW_REQUIRED':'READY_WITH_DEFAULTS');return $this->item('client','clientes',$r['id']??null,$status,$exists?'CONFLICT':($invalid?'SKIP':($status==='REVIEW_REQUIRED'?'REVIEW':'INSERT')),['source'=>$r,'destination'=>['company_name'=>$r['legal_name']??null,'vat_number'=>$rfc,'zip'=>$r['postal_code']??null,'phone'=>$r['phone']??null,'email'=>$r['email']??null,'fiscal_profile'=>['legal_name'=>$r['legal_name']??null,'rfc'=>$rfc,'fiscal_postal_code'=>$r['postal_code']??null,'tax_regime_code'=>$r['fiscal_regime']??null,'cfdi_use_code'=>$o['default_cfdi_use'],'cfdi_use_origin'=>'DEFAULT','fiscal_street'=>$r['street']??null,'fiscal_external_number'=>$r['exterior_number']??null,'fiscal_internal_number'=>$r['interior_number']??null,'fiscal_neighborhood'=>$r['neighborhood']??null,'fiscal_locality'=>$r['locality']??null,'fiscal_municipality'=>$r['municipality']??null,'fiscal_state'=>$r['state']??null,'fiscal_country_code'=>$r['country']??'MEX'],'exists'=>$exists],'lookups'=>['tax_regime'=>$reg,'cfdi_use'=>$use]],$w);}
 private function product(array $r,array $o,array $c,array $dups):array{$w=[];$code=trim((string)($r['code']??''));if($code===''||!filled($r['description']??null))$w[]='Clave o descripción vacía.';if(isset($dups[Str::upper($code)]))$w[]='DUPLICATE_PRODUCT_CODE';$sp=$this->lookup($c,'product_keys',(string)($r['sat_product_code']??''));$su=$this->lookup($c,'unit_keys',(string)($r['sat_unit_code']??''));if(!$sp['matched'])$w[]='ClaveProdServ no encontrada.';if(!$su['matched'])$w[]='ClaveUnidad no encontrada.';$to=$this->lookup($c,'tax_objects',$o['default_tax_object']);if($c['selected']&&!$to['matched'])$w[]='ObjetoImp default no existe en destino.';if($o['prepare_products']&&$c['selected']&&!$c['tax']['matched'])$w[]='IVA 16% fiscal no existe exactamente en destino.';$known=filled($r['tax']??null);$exists=in_array(Str::upper($code),$c['product_codes'],true);$status=($code===''||!filled($r['description']??null))?'INVALID':($w?'REVIEW_REQUIRED':($known?'READY':'READY_WITH_DEFAULTS'));return $this->item('product','productos',$r['id']??null,$status,$exists?'CONFLICT':($status==='INVALID'?'SKIP':(str_contains($status,'REVIEW')?'REVIEW':'INSERT')),['source'=>$r,'destination'=>['identification_number'=>$code,'title'=>$r['description']??null,'rate'=>(string)($r['price']??'0'),'unit_type'=>$r['unit']??null,'fiscal_setting'=>['fiscal_description'=>$r['description']??null,'sat_product_code'=>$r['sat_product_code']??null,'sat_unit_code'=>$r['sat_unit_code']??null,'tax_object_code'=>$o['default_tax_object'],'tax_object_origin'=>'DEFAULT'],'tax'=>['code'=>'002','name'=>'IVA','percentage'=>'16','fiscal_tax_type'=>'transfer','origin'=>$known?'FC':'DEFAULT','apply'=>$o['prepare_products']&&($known||$o['apply_default_tax']||$o['force_default_tax'])],'exists'=>$exists],'lookups'=>['sat_product'=>$sp,'sat_unit'=>$su,'tax_object'=>$to,'tax'=>$c['tax']]],$w);}
 private function csd(array $c):array{$until=data_get($c,'info.valid_until');$expired=$until&&strtotime($until)<time();$status=!($c['has_cer']??false)||!($c['has_key']??false)?'INCOMPLETE':($expired?'EXPIRED':'READY_TO_IMPORT');return $this->item('csd','users_info_factura',null,$status,$status==='READY_TO_IMPORT'?'REVIEW':'SKIP',['certificate_found'=>(bool)($c['has_cer']??false),'key_found'=>(bool)($c['has_key']??false),'certificate_number'=>data_get($c,'info.certificate_number'),'valid_from'=>data_get($c,'info.valid_from'),'valid_until'=>$until,'import_policy'=>'Use secure iKontrol certificate importer; binary and password excluded.']);}
 private function series(array $r,array $o,array $c):array{$key=Str::upper(($r['type']??'').'|'.($r['series']??''));$conflict=in_array($key,$c['series'],true);return $this->item('series','folios',$r['id']??null,$conflict?'REVIEW_REQUIRED':'READY',$conflict?'CONFLICT':($o['preserve_series']?'INSERT':'SKIP'),['source'=>$r,'destination'=>['document_type'=>$r['type']??null,'series'=>$r['series']??null,'current_folio'=>$r['current_folio']??null],'preserve'=>$o['preserve_series']],$conflict?['Serie ya existe en destino.']:[]);}
 private function item(string $type,string $table,mixed $id,string $status,string $action,array $preview,array $warnings=[]):array{$safe=$this->sanitize($preview);return ['entity_type'=>$type,'source_table'=>$table,'source_id'=>$id===null?null:(string)$id,'proposed_action'=>$action,'validation_status'=>$status,'source_hash'=>hash('sha256',json_encode($safe,JSON_UNESCAPED_UNICODE|JSON_PRESERVE_ZERO_FRACTION)),'warnings_json'=>$warnings,'preview_json'=>$safe];}
 private function duplicates(array $rows,string $field):array{$g=[];foreach($rows as $r){$v=Str::upper(trim((string)($r[$field]??'')));if($v!=='')$g[$v][]=$r['id']??null;}return array_filter($g,fn($ids)=>count($ids)>1);}
 private function summary(array $s,array $items,array $dr,array $dp):array{$counts=[];foreach(['issuer','client','product','csd','series'] as $type){$rows=array_values(array_filter($items,fn($i)=>$i['entity_type']===$type));$counts[$type]=['total'=>count($rows),'statuses'=>array_count_values(array_column($rows,'validation_status'))];}return $counts+['client_unique_rfcs'=>count($s['clients'])-array_sum(array_map(fn($x)=>count($x)-1,$dr)),'client_duplicate_groups'=>count($dr),'product_unique_codes'=>count($s['products'])-array_sum(array_map(fn($x)=>count($x)-1,$dp)),'product_duplicate_groups'=>count($dp),'historical'=>['invoices'=>data_get($s,'invoices.total'),'complements'=>data_get($s,'invoices.complements'),'cancellations'=>data_get($s,'invoices.cancellations'),'strategy'=>'NOT_PLANNED']];}
 private function overallStatus(array $i,array $c):string{if($c['selected']&&!$c['schema_ready'])return'BLOCKED';$s=array_column($i,'validation_status');return array_intersect($s,['INVALID','INCOMPLETE','REVIEW_REQUIRED','EXPIRED'])?'READY_WITH_WARNINGS':'READY';}
 private function fingerprint(array $s):string{return hash('sha256',json_encode(['user'=>$s['users_id'],'rfc'=>$s['rfc'],'profile'=>$s['profile'],'clients'=>$s['clients'],'products'=>$s['products'],'folios'=>$s['folios'],'counts'=>$s['summary']],JSON_UNESCAPED_UNICODE|JSON_PRESERVE_ZERO_FRACTION));}
 private function validRfc(string $r):bool{return(bool)preg_match('/^[A-ZÑ&]{3,4}\d{6}[A-Z0-9]{3}$/',Str::upper(trim($r)));}
 private function sanitize(array $v):array{foreach($v as $k=>$x){if(preg_match('/password|secret|token|api.?key|private|binary|xml/i',(string)$k))unset($v[$k]);elseif(is_array($x))$v[$k]=$this->sanitize($x);}return$v;}
 private function lookup(array $c,string $g,string $code):array{$code=Str::upper(trim($code));return['code'=>$code,'matched'=>!$c['selected']?$code!=='':isset($c[$g][$code]),'destination_id'=>$c[$g][$code]??null,'verification'=>$c['selected']?'DESTINATION':'FORMAT_ONLY'];}
 private function emptyDestination():array{return['selected'=>false,'schema_ready'=>true,'instance'=>null,'regimes'=>[],'cfdi_uses'=>[],'product_keys'=>[],'unit_keys'=>[],'tax_objects'=>[],'tax'=>['matched'=>true,'id'=>null],'client_rfcs'=>[],'product_codes'=>[],'series'=>[]];}
 private function destination(int $id):array{$instance=IkontrolInstance::findOrFail($id);return$this->instances->withInstanceConnection($instance,fn(Connection $db)=>$this->inspectDestination($db,$instance));}
 private function inspectDestination(Connection $db,IkontrolInstance $instance):array{$tables=['regimes'=>'ikontrol_sat_tax_regimes','cfdi_uses'=>'ikontrol_sat_cfdi_uses','product_keys'=>'ikontrol_sat_product_service_keys','unit_keys'=>'ikontrol_sat_unit_keys','tax_objects'=>'ikontrol_sat_tax_object_codes'];$r=$this->emptyDestination();$r['selected']=true;$r['instance']=['id'=>$instance->id,'name'=>$instance->name];foreach($tables as $k=>$t){if(!$db->getSchemaBuilder()->hasTable($t)){$r['schema_ready']=false;continue;}$cols=$db->getSchemaBuilder()->getColumnListing($t);$code=collect(['code','key','clave'])->first(fn($x)=>in_array($x,$cols,true));if(!$code){$r['schema_ready']=false;continue;}$r[$k]=$db->table($t)->pluck('id',$code)->mapWithKeys(fn($v,$x)=>[Str::upper(trim((string)$x))=>$v])->all();}$r['client_rfcs']=$this->pluckUpper($db,'ikontrol_clients',['vat_number','rfc']);$r['product_codes']=$this->pluckUpper($db,'ikontrol_items',['identification_number','code']);$r['series']=$this->seriesKeys($db);$r['tax']=$this->findVat($db);return$r;}
 private function pluckUpper(Connection $db,string $t,array $cols):array{if(!$db->getSchemaBuilder()->hasTable($t))return[];$have=$db->getSchemaBuilder()->getColumnListing($t);$col=collect($cols)->first(fn($x)=>in_array($x,$have,true));return$col?$db->table($t)->whereNotNull($col)->pluck($col)->map(fn($x)=>Str::upper(trim((string)$x)))->all():[];}
 private function seriesKeys(Connection $db):array{if(!$db->getSchemaBuilder()->hasTable('ikontrol_fiscal_series'))return[];$c=$db->getSchemaBuilder()->getColumnListing('ikontrol_fiscal_series');if(!in_array('series',$c,true))return[];$type=in_array('document_type',$c,true)?'document_type':(in_array('type',$c,true)?'type':null);return$db->table('ikontrol_fiscal_series')->get()->map(fn($x)=>Str::upper(($type?$x->{$type}:'').'|'.$x->series))->all();}
 private function findVat(Connection $db):array{if(!$db->getSchemaBuilder()->hasTable('ikontrol_taxes'))return['matched'=>false,'id'=>null];$c=$db->getSchemaBuilder()->getColumnListing('ikontrol_taxes');$q=$db->table('ikontrol_taxes');if(in_array('percentage',$c,true))$q->where('percentage',16);if(in_array('title',$c,true))$q->whereRaw('UPPER(title) LIKE ?',['%IVA%']);if(in_array('fiscal_tax_type',$c,true))$q->where('fiscal_tax_type','transfer');if(in_array('use_for_fiscal',$c,true))$q->where('use_for_fiscal',1);$row=$q->first();return['matched'=>(bool)$row,'id'=>$row->id??null];}
}