@extends('layouts/layoutMaster')
@section('title','Nueva instalación')
@section('content')
<div class="mb-6"><h4 class="mb-1">Nueva instalación</h4><p class="text-body-secondary mb-0">Provisioning controlado desde una versión limpia de iKontrol.</p></div>
<div class="card"><div class="card-body pt-6">@include('admin.partials.flash')
<form method="POST" action="{{ route('provisioning.store') }}" id="provision-form">@csrf<div class="row g-5">
<div class="col-md-6"><label class="form-label">Cliente existente</label><select class="form-select" name="client_id"><option value="">Seleccione...</option>@foreach($clients as $client)<option value="{{ $client->id }}">{{ $client->name }}</option>@endforeach</select><input type="hidden" name="client_mode" value="existing"></div>
<div class="col-md-6"><label class="form-label">Nombre de instalación</label><input class="form-control" name="name" required></div>
<div class="col-md-6"><label class="form-label">Slug</label><input class="form-control" name="slug" id="slug" pattern="[a-z0-9]+(?:_[a-z0-9]+)*" required></div>
<div class="col-md-6"><label class="form-label">Versión iKontrol</label><select class="form-select" name="ikontrol_version_id" id="version" required><option value="">Seleccione...</option>@foreach($versions as $version)<option value="{{ $version->id }}" @selected($version->is_default)>{{ $version->name }} ({{ $version->version }})</option>@endforeach</select></div>
<div class="col-12"><div class="card bg-lighter shadow-none"><div class="card-body"><div class="row g-4"><div class="col-md-6"><small class="text-body-secondary d-block">Dominio esperado</small><code id="domain">https://&lt;slug&gt;.ikontrol.solutions</code></div><div class="col-md-6"><small class="text-body-secondary d-block">Carpeta</small><code id="folder" class="text-break">{{ rtrim(config('ikontrol.instances_root'),'/\\') }}/&lt;slug&gt;{{ config('ikontrol.folder_suffix') }}</code></div><div class="col-md-6"><small class="text-body-secondary d-block">Base</small><code id="database">{{ config('ikontrol.db.prefix') }}&lt;slug&gt;</code></div><div class="col-md-6"><small class="text-body-secondary d-block">Versión</small><code id="selected-version">-</code></div></div></div></div></div>
<div class="col-12"><div id="checks" class="mb-4"></div><div class="alert alert-warning">Se creará la carpeta, la base y el código de la versión seleccionada. El dominio NO será creado automáticamente.</div><button type="button" id="preflight" class="btn btn-outline-primary me-2">Ejecutar preflight</button><button type="button" id="dry-run" class="btn btn-outline-secondary me-2">Simular instalación</button><button id="create" class="btn btn-primary" disabled>Crear instalación</button></div>
</div></form></div></div>
@endsection
@section('page-script')<script>
document.addEventListener('DOMContentLoaded',()=>{const form=document.getElementById('provision-form'),slug=document.getElementById('slug'),version=document.getElementById('version'),create=document.getElementById('create'),checks=document.getElementById('checks');const update=()=>{const s=slug.value||'<slug>';document.getElementById('domain').textContent=`https://${s}.ikontrol.solutions`;document.getElementById('folder').textContent=@json(rtrim(config('ikontrol.instances_root'),'/\\').'/')+s+@json(config('ikontrol.folder_suffix'));document.getElementById('database').textContent=@json(config('ikontrol.db.prefix'))+s;document.getElementById('selected-version').textContent=version.selectedOptions[0]?.text||'-';create.disabled=true;checks.innerHTML='';};const run=async(url)=>{const response=await fetch(url,{method:'POST',headers:{Accept:'application/json'},body:new FormData(form)});const result=await response.json();checks.innerHTML=`<div class="alert alert-${result.success?'success':'warning'}">${Object.entries(result.checks||{}).map(([key,value])=>`<div>${value?'OK':'FALLO'}: ${key}</div>`).join('')}</div>`;create.disabled=!result.success;};slug.addEventListener('input',update);version.addEventListener('change',update);document.getElementById('preflight').addEventListener('click',()=>run(@json(route('provisioning.preflight'))));document.getElementById('dry-run').addEventListener('click',()=>run(@json(route('provisioning.dry-run'))));form.addEventListener('submit',e=>{if(!confirm(`Se creará:\n\nCarpeta: ${document.getElementById('folder').textContent}\nBase: ${document.getElementById('database').textContent}\nUsuario MySQL: ${@json(config('ikontrol.db.username'))}\nVersión: ${document.getElementById('selected-version').textContent}\nDominio esperado: ${document.getElementById('domain').textContent}\n\nEl dominio NO será creado automáticamente.`))e.preventDefault();});update();});
</script>
@endsection
