@extends('layouts/layoutMaster')
@section('title','Nueva instalación')
@section('content')
<div class="mb-6"><h4 class="mb-1">Nueva instalación</h4><p class="text-body-secondary mb-0">Provisioning controlado desde una plantilla validada de código + base.</p></div>
<div class="card"><div class="card-body pt-6">@include('admin.partials.flash')
<form method="POST" action="{{ route('provisioning.store') }}" id="provision-form">@csrf<div class="row g-5">
<div class="col-12"><label class="form-label d-block">Cliente</label><div class="d-flex flex-column flex-sm-row gap-4"><label class="form-check custom-option custom-option-basic flex-fill"><span class="form-check-label custom-option-content"><input class="form-check-input" type="radio" name="client_mode" value="existing" @checked(old('client_mode','existing')==='existing')> Usar cliente existente</span></label><label class="form-check custom-option custom-option-basic flex-fill"><span class="form-check-label custom-option-content"><input class="form-check-input" type="radio" name="client_mode" value="new" @checked(old('client_mode')==='new')> Crear cliente nuevo</span></label></div></div>
<div class="col-md-6" id="existing-client-field"><label class="form-label">Cliente existente</label><select class="form-select" name="client_id" id="client-id"><option value="">Seleccione...</option>@foreach($clients as $client)<option value="{{ $client->id }}" @selected(old('client_id')==$client->id)>{{ $client->name }}</option>@endforeach</select></div>
<div class="col-md-6 d-none" id="new-client-field"><label class="form-label">Nombre del cliente nuevo</label><input class="form-control" name="new_client_name" id="new-client-name" value="{{ old('new_client_name') }}"></div>
<div class="col-md-6"><label class="form-label">Nombre de instalación</label><input class="form-control" name="name" value="{{ old('name') }}" required></div>
<div class="col-md-6"><label class="form-label">Slug</label><input class="form-control" name="slug" id="slug" value="{{ old('slug') }}" pattern="[a-z0-9]+(?:_[a-z0-9]+)*" required></div>
<div class="col-md-6"><label class="form-label">Versión iKontrol</label><select class="form-select" name="ikontrol_template_id" id="template" required><option value="">Seleccione...</option>@foreach($templates as $template)<option value="{{ $template->id }}" data-app="{{ $template->app_version }}" data-schema="{{ $template->schema_version }}" @selected(old('ikontrol_template_id',$template->is_default?$template->id:null)==$template->id)>{{ $template->name }} — App {{ $template->app_version }} — Schema {{ $template->schema_version }}</option>@endforeach</select></div>
<div class="col-12"><label class="form-check"><input class="form-check-input" type="checkbox" name="is_test" value="1" @checked(old('is_test'))><span class="form-check-label">Instalación de prueba/desarrollo (habilita reinicio y eliminación protegidos)</span></label></div>
<div class="col-12"><div class="card bg-lighter shadow-none"><div class="card-body"><div class="row g-4"><div class="col-md-6"><small class="text-body-secondary d-block">Dominio esperado</small><code id="domain">https://&lt;slug&gt;.ikontrol.solutions</code></div><div class="col-md-6"><small class="text-body-secondary d-block">Carpeta</small><code id="folder" class="text-break"></code></div><div class="col-md-4"><small class="text-body-secondary d-block">Base</small><code id="database"></code></div><div class="col-md-4"><small class="text-body-secondary d-block">Versión app</small><code id="selected-app">-</code></div><div class="col-md-4"><small class="text-body-secondary d-block">Versión schema</small><code id="selected-schema">-</code></div></div></div></div></div>
<div class="col-12"><div id="checks" class="mb-4"></div><div class="alert alert-warning">Se crearán carpeta, base, código y schema desde la plantilla. El dominio no será creado automáticamente.</div><button type="button" id="preflight" class="btn btn-outline-primary me-2">Ejecutar preflight</button><button type="button" id="dry-run" class="btn btn-outline-secondary me-2">Simular</button><button id="create" class="btn btn-primary" disabled>Crear instalación</button></div>
</div></form></div></div>
@endsection
@section('page-script')<script>
document.addEventListener('DOMContentLoaded',()=>{const form=document.getElementById('provision-form'),slug=document.getElementById('slug'),template=document.getElementById('template'),create=document.getElementById('create'),checks=document.getElementById('checks'),existing=document.getElementById('existing-client-field'),fresh=document.getElementById('new-client-field'),clientId=document.getElementById('client-id'),clientName=document.getElementById('new-client-name'),domain=document.getElementById('domain'),folder=document.getElementById('folder'),database=document.getElementById('database'),preflight=document.getElementById('preflight');const update=()=>{const s=slug.value||'<slug>',o=template.selectedOptions[0];domain.textContent=`https://${s}.ikontrol.solutions`;folder.textContent=@json(rtrim(config('ikontrol.instances_root'),'/\\').'/')+s+@json(config('ikontrol.folder_suffix'));database.textContent=@json(config('ikontrol.db.prefix'))+s;document.getElementById('selected-app').textContent=o?.dataset.app||'-';document.getElementById('selected-schema').textContent=o?.dataset.schema||'-';create.disabled=true;checks.innerHTML='';};const mode=()=>{const useExisting=document.querySelector('[name="client_mode"]:checked').value==='existing';existing.classList.toggle('d-none',!useExisting);fresh.classList.toggle('d-none',useExisting);clientId.disabled=!useExisting;clientName.disabled=useExisting;update();};const run=async url=>{const response=await fetch(url,{method:'POST',headers:{Accept:'application/json'},body:new FormData(form)}),result=await response.json();if(!response.ok){checks.innerHTML='<div class="alert alert-danger">Revise cliente, instalación y plantilla.</div>';return;}checks.innerHTML=`<div class="alert alert-${result.success?'success':'warning'}">${Object.entries(result.checks||{}).map(([k,v])=>`<div>${v?'OK':'FALLO'}: ${k}</div>`).join('')}</div>`;create.disabled=!result.success;};document.querySelectorAll('[name="client_mode"]').forEach(e=>e.addEventListener('change',mode));slug.addEventListener('input',update);template.addEventListener('change',update);preflight.addEventListener('click',()=>run(@json(route('provisioning.preflight'))));document.getElementById('dry-run').addEventListener('click',()=>run(@json(route('provisioning.dry-run'))));form.addEventListener('submit',e=>{if(!confirm(`Se creará:\n\nCarpeta: ${folder.textContent}\nBase: ${database.textContent}\nUsuario MySQL: ${@json(config('ikontrol.db.username'))}\nApp: ${document.getElementById('selected-app').textContent}\nSchema: ${document.getElementById('selected-schema').textContent}\nDominio: ${domain.textContent}\n\nEl dominio NO será creado automáticamente.`))e.preventDefault();});mode();});
</script>@endsection
