@extends('layouts/layoutMaster')
@section('title','Nueva instalación')
@section('content')
<div class="mb-6"><h4 class="mb-1">Nueva instalación</h4><p class="text-body-secondary mb-0">Prepare de forma controlada una nueva instancia iKontrol.</p></div>
<div class="card mb-6"><div class="card-body"><div class="row g-3 text-center">
@foreach([['1','Cliente','tabler-user'],['2','Instalación','tabler-server'],['3','Preflight','tabler-list-check'],['4','Preparar','tabler-rocket'],['5','Resultado','tabler-circle-check']] as [$number,$label,$icon])<div class="col"><div class="avatar mx-auto mb-2"><span class="avatar-initial rounded bg-label-{{ $loop->first?'primary':'secondary' }}"><i class="icon-base ti {{ $icon }}"></i></span></div><small class="d-none d-sm-block fw-medium">{{ $number }}. {{ $label }}</small></div>@endforeach
</div></div></div>
<div class="card"><div class="card-header border-bottom"><h5 class="mb-1">Datos de la instalación</h5><small class="text-body-secondary">El backend construye la carpeta y el nombre de base; nunca se aceptan rutas absolutas.</small></div><div class="card-body pt-6">@include('admin.partials.flash')
<form method="POST" action="{{ route('provisioning.store') }}" id="provision-form">@csrf<div class="row g-5"><div class="col-md-6"><label class="form-label">Cliente existente</label><select class="form-select" name="client_id"><option value="">Crear cliente nuevo</option>@foreach($clients as $c)<option value="{{ $c->id }}" @selected(old('client_id')==$c->id)>{{ $c->name }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">Nombre del cliente nuevo</label><input class="form-control" name="new_client_name" value="{{ old('new_client_name') }}" placeholder="Solo si no seleccionó un cliente"></div><div class="col-md-6"><label class="form-label">Nombre de instalación</label><input class="form-control" name="name" value="{{ old('name') }}" required></div><div class="col-md-6"><label class="form-label">Slug</label><div class="input-group"><span class="input-group-text"><i class="icon-base ti tabler-link"></i></span><input class="form-control" name="slug" id="slug" value="{{ old('slug') }}" pattern="[a-z0-9]+(?:_[a-z0-9]+)*" placeholder="dmarco" required></div><div class="form-text">Minúsculas, números y guion bajo.</div></div>
<div class="col-12"><div class="card bg-lighter shadow-none"><div class="card-body"><h6 class="mb-4"><i class="icon-base ti tabler-eye me-2"></i>Vista previa</h6><div class="row g-4"><div class="col-lg-6"><small class="text-body-secondary d-block">Carpeta</small><code id="folder" class="text-break">{{ rtrim(config('ikontrol.instances_root'),'/\\') }}/&lt;slug&gt;{{ config('ikontrol.folder_suffix') }}</code></div><div class="col-lg-6"><small class="text-body-secondary d-block">Base de datos</small><code id="database" class="text-break">{{ config('ikontrol.db.prefix') }}&lt;slug&gt;</code></div></div></div></div></div>
<div class="col-12"><div id="checks" class="mb-4"></div><div class="d-flex flex-column flex-sm-row gap-3"><button type="button" id="preflight" class="btn btn-outline-primary"><i class="icon-base ti tabler-list-check me-2"></i>Ejecutar preflight</button><button id="create" class="btn btn-primary" disabled onclick="return confirm('Se crearán carpeta y base de datos. ¿Continuar?')"><i class="icon-base ti tabler-rocket me-2"></i>Crear instalación base</button></div></div></div></form>
</div></div>
@endsection
@section('page-script')<script>document.addEventListener('DOMContentLoaded',()=>{const s=document.getElementById('slug'),f=document.getElementById('folder'),d=document.getElementById('database'),b=document.getElementById('create'),checks=document.getElementById('checks');s.addEventListener('input',()=>{f.textContent=@json(rtrim(config('ikontrol.instances_root'),'/\\').'/')+s.value+@json(config('ikontrol.folder_suffix'));d.textContent=@json(config('ikontrol.db.prefix'))+s.value;b.disabled=true;checks.innerHTML=''});document.getElementById('preflight').addEventListener('click',async()=>{const r=await fetch(@json(route('provisioning.preflight')),{method:'POST',headers:{Accept:'application/json'},body:new FormData(document.getElementById('provision-form'))});const x=await r.json();if(!r.ok){checks.innerHTML='<div class="alert alert-danger mb-0">Revise los campos requeridos antes de continuar.</div>';return}checks.innerHTML='<div class="alert alert-'+(x.success?'success':'warning')+'"><h6 class="alert-heading mb-3">Resultado del preflight</h6>'+Object.entries(x.checks).map(([k,v])=>`<span class="badge bg-label-${v?'success':'danger'} me-2 mb-2">${v?'✓':'×'} ${k.replaceAll('_',' ')}</span>`).join('')+'</div>';b.disabled=!x.success})})</script>@endsection
