@extends('layouts/layoutMaster')
@section('title','Versiones iKontrol')
@section('content')
<div class="d-flex justify-content-between align-items-center mb-6"><div><h4 class="mb-1">Versiones iKontrol</h4><p class="text-body-secondary mb-0">Cada versión válida combina código ZIP y base SQL compatibles.</p></div><a href="{{ route('versions.create') }}" class="btn btn-primary">Nueva versión</a></div>
@include('admin.partials.flash')
<div class="card"><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Versión</th><th>Aplicación</th><th>Schema</th><th>Archivos</th><th>Estado</th><th></th></tr></thead><tbody>
@foreach($templates as $template)<tr><td><strong>{{ $template->name }}</strong><br><small>{{ $template->version }}</small></td><td>{{ $template->app_version }}</td><td>{{ $template->schema_version }}</td><td><code>{{ $template->archive_path }}</code><br><code>{{ $template->database_dump_path }}</code></td><td>@if($validity[$template->id])<span class="badge bg-label-success">VALID</span>@else<span class="badge bg-label-danger">INVALID</span>@endif @unless($template->active)<span class="badge bg-label-secondary">INACTIVE</span>@endunless @if($template->is_default)<span class="badge bg-label-primary">DEFAULT</span>@endif</td><td><a href="{{ route('versions.templates.edit',$template) }}" class="btn btn-sm btn-outline-primary">Editar</a></td></tr>@endforeach
@foreach($legacyVersions as $version)<tr><td><strong>{{ $version->name }}</strong><br><small>{{ $version->version }}</small></td><td>{{ $version->version }}</td><td><span class="text-body-secondary">Por completar</span></td><td><code>{{ $version->source_reference }}</code><br><span class="text-body-secondary">SQL pendiente</span></td><td><span class="badge bg-label-danger">INVALID</span> @unless($version->active)<span class="badge bg-label-secondary">INACTIVE</span>@endunless</td><td><a href="{{ route('versions.edit',$version) }}" class="btn btn-sm btn-outline-warning">Completar</a></td></tr>@endforeach
@if($templates->isEmpty() && $legacyVersions->isEmpty())<tr><td colspan="6" class="text-center py-6">No hay versiones registradas.</td></tr>@endif
</tbody></table></div></div>
@endsection
