@extends('layouts/layoutMaster')
@section('title',$template->exists?'Editar plantilla':'Nueva plantilla')
@section('content')
<h4 class="mb-6">{{ $template->exists?'Editar plantilla':'Nueva plantilla iKontrol' }}</h4>
<div class="card"><div class="card-body"><div class="alert alert-info">Los archivos deben existir previamente bajo <code>{{ config('ikontrol.templates.root') }}/&lt;versión&gt;/</code>. Código y SQL son obligatorios.</div>
<form method="POST" action="{{ $template->exists?route('templates.update',$template):route('templates.store') }}">@csrf @if($template->exists)@method('PUT')@endif
<div class="row g-5">@foreach(['version'=>'Versión','name'=>'Nombre','app_version'=>'Versión app','schema_version'=>'Versión schema','archive_path'=>'Ruta ZIP relativa','database_dump_path'=>'Ruta SQL relativa','archive_sha256'=>'SHA-256 ZIP','database_sha256'=>'SHA-256 SQL'] as $field=>$label)<div class="col-md-6"><label class="form-label">{{ $label }}</label><input name="{{ $field }}" class="form-control @error($field)is-invalid @enderror" value="{{ old($field,$template->$field) }}" required>@error($field)<div class="invalid-feedback">{{ $message }}</div>@enderror</div>@endforeach
<div class="col-12"><label class="form-label">Notas</label><textarea name="notes" class="form-control">{{ old('notes',$template->notes) }}</textarea></div><div class="col-md-3 form-check form-switch ms-3"><input type="checkbox" class="form-check-input" name="active" value="1" @checked(old('active',$template->active))><label class="form-check-label">Activa</label></div><div class="col-md-3 form-check form-switch"><input type="checkbox" class="form-check-input" name="is_default" value="1" @checked(old('is_default',$template->is_default))><label class="form-check-label">Predeterminada</label></div><div class="col-12"><button class="btn btn-primary">Guardar y validar</button> <a href="{{ route('templates.index') }}" class="btn btn-label-secondary">Cancelar</a></div></div></form></div></div>
@endsection
