<?php

use App\Http\Controllers\Admin\{AuditLogController, ClientController, ConfigurationController, DashboardController, IkontrolVersionController, InstanceController, InstanceDiagnosticsController, InstanceOperationController, InstanceUpgradeController, LegacyFactucareController, FactucareConversionController, LoginController, ProvisioningController};
use Illuminate\Support\Facades\Route;

Route::middleware('guest')->group(function () {
    Route::get('/login', [LoginController::class, 'create'])->name('login');
    Route::post('/login', [LoginController::class, 'store'])->middleware('throttle:5,1')->name('login.store');
});
Route::middleware('auth')->group(function () {
    Route::get('/', DashboardController::class)->name('dashboard');
    Route::post('/logout', [LoginController::class, 'destroy'])->name('logout');
    Route::resource('clients', ClientController::class)->except('destroy');
    Route::patch('/clients/{client}/toggle', [ClientController::class, 'toggle'])->name('clients.toggle');
    Route::get('/instances', [InstanceController::class, 'index'])->name('instances.index');
    Route::get('/instances/register', [InstanceController::class, 'create'])->name('instances.create');
    Route::post('/instances', [InstanceController::class, 'store'])->name('instances.store');
    Route::get('/instances/{instance}', [InstanceController::class, 'show'])->name('instances.show');
    Route::post('/instances/{instance}/test', [InstanceController::class, 'testConnection'])->middleware('throttle:10,1')->name('instances.test');
    Route::post('/instances/{instance}/inspect', [InstanceController::class, 'inspect'])->middleware('throttle:5,1')->name('instances.inspect');
    Route::patch('/instances/{instance}/update-channel', [InstanceController::class, 'updateChannel'])->middleware('throttle:10,1')->name('instances.update-channel');
    Route::post('/instances/{instance}/upgrade-audits', [InstanceUpgradeController::class, 'analyze'])->middleware('throttle:3,1')->name('instances.upgrade-audits.analyze');
    Route::post('/instances/{instance}/version-inspection', [InstanceUpgradeController::class, 'inspect'])->middleware('throttle:5,1')->name('instances.version.inspect');
    Route::post('/instances/{instance}/upgrade-plan', [InstanceUpgradeController::class, 'plan'])->middleware('throttle:3,1')->name('instances.upgrade.plan');
    Route::post('/instances/{instance}/releases/{release}/prepare', [InstanceUpgradeController::class, 'prepareDeployment'])->middleware('throttle:3,1')->name('instances.releases.prepare');
    Route::get('/instances/{instance}/update-runs/{updateRun}', [InstanceUpgradeController::class, 'showDeployment'])->name('instances.update-runs.show');
    Route::post('/instances/{instance}/update-runs/{updateRun}/execute', [InstanceUpgradeController::class, 'executeDeployment'])->middleware('throttle:1,1')->name('instances.update-runs.execute');
    Route::post('/instances/{instance}/adoption-plan', [InstanceUpgradeController::class, 'adoptionPlan'])->middleware('throttle:3,1')->name('instances.adoption.plan');
    Route::get('/instances/{instance}/upgrade-audits/{upgradeAudit}', [InstanceUpgradeController::class, 'show'])->name('instances.upgrade-audits.show');
    Route::post('/instances/{instance}/upgrade-audits/{upgradeAudit}/dry-run', [InstanceUpgradeController::class, 'dryRun'])->middleware('throttle:5,1')->name('instances.upgrade-audits.dry-run');
    Route::post('/instances/{instance}/upgrade-audits/{upgradeAudit}/execute', [InstanceUpgradeController::class, 'execute'])->middleware('throttle:2,1')->name('instances.upgrade.execute');
    Route::post('/instances/{instance}/upgrade-audits/{upgradeAudit}/adopt', [InstanceUpgradeController::class, 'adopt'])->middleware('throttle:2,1')->name('instances.adoption.execute');
    Route::post('/instances/{instance}/operations/{operation}', [InstanceOperationController::class, 'run'])->whereIn('operation',['files','database','reassign-user','key','cache','migrate','health'])->middleware('throttle:10,1')->name('instances.operations.run');
    Route::post('/instances/{instance}/administrators/{operation}', [InstanceOperationController::class, 'admin'])->whereIn('operation',['create','reset'])->middleware('throttle:5,1')->name('instances.operations.admin');
    Route::post('/instances/{instance}/stamps', [InstanceDiagnosticsController::class,'stamps'])->middleware('throttle:5,1')->name('instances.stamps.move');
    Route::get('/instances/{instance}/logs/{file}', [InstanceDiagnosticsController::class,'log'])->where('file','[A-Za-z0-9._-]+\\.log')->middleware('throttle:30,1')->name('instances.logs.show');
    Route::post('/instances/{instance}/logs/clear', [InstanceDiagnosticsController::class,'clearLogs'])->middleware('throttle:3,1')->name('instances.logs.clear');
    Route::post('/instances/{instance}/logs/check', [InstanceDiagnosticsController::class,'logCheck'])->middleware('throttle:5,1')->name('instances.logs.check');
    Route::post('/instances/{instance}/diagnostics/{type}', [InstanceDiagnosticsController::class,'diagnose'])->whereIn('type',['admin','dashboard'])->middleware('throttle:10,1')->name('instances.diagnostics.run');
    Route::post('/instances/{instance}/diagnostic', [InstanceDiagnosticsController::class,'comprehensive'])->middleware('throttle:5,1')->name('instances.diagnostic.run');
    Route::post('/instances/{instance}/diagnostic/tools', [InstanceDiagnosticsController::class,'installTools'])->middleware('throttle:3,1')->name('instances.diagnostic.tools');
    Route::post('/instances/{instance}/diagnostic/writable', [InstanceDiagnosticsController::class,'repairWritable'])->middleware('throttle:3,1')->name('instances.diagnostic.writable');
    Route::post('/instances/{instance}/destructive/{operation}', [InstanceOperationController::class, 'destructive'])->whereIn('operation',['restart','delete'])->middleware('throttle:2,1')->name('instances.operations.destructive');
    Route::get('/provisioning/new', [ProvisioningController::class, 'create'])->name('provisioning.create');
    Route::post('/provisioning/preflight', [ProvisioningController::class, 'preflight'])->name('provisioning.preflight');
    Route::post('/provisioning/dry-run', [ProvisioningController::class, 'dryRun'])->name('provisioning.dry-run');
    Route::post('/provisioning', [ProvisioningController::class, 'store'])->middleware('throttle:3,1')->name('provisioning.store');
    Route::post('/provisioning/{instance}/retry', [ProvisioningController::class, 'retry'])->middleware('throttle:3,1')->name('provisioning.retry');
    Route::post('/provisioning/{instance}/confirm-domain', [ProvisioningController::class, 'confirmDomain'])->middleware('throttle:3,1')->name('provisioning.confirm-domain');
    Route::post('/provisioning/{instance}/regenerate-configuration', [ProvisioningController::class, 'regenerateConfiguration'])->middleware('throttle:3,1')->name('provisioning.regenerate-configuration');
    Route::get('/versions', [IkontrolVersionController::class, 'index'])->name('versions.index');
    Route::post('/versions/sync', [IkontrolVersionController::class, 'sync'])->middleware('throttle:3,1')->name('versions.sync');
    Route::get('/versions/releases/{release}/manifest', [IkontrolVersionController::class, 'manifest'])->name('versions.releases.manifest');
    Route::get('/versions/create', [IkontrolVersionController::class, 'create'])->name('versions.create');
    Route::post('/versions', [IkontrolVersionController::class, 'store'])->name('versions.store');
    Route::get('/versions/templates/{template}/edit', [IkontrolVersionController::class, 'editTemplate'])->name('versions.templates.edit');
    Route::put('/versions/templates/{template}', [IkontrolVersionController::class, 'updateTemplate'])->name('versions.templates.update');
    Route::get('/versions/{version}/edit', [IkontrolVersionController::class, 'editLegacy'])->name('versions.edit');
    Route::put('/versions/{version}', [IkontrolVersionController::class, 'completeLegacy'])->name('versions.update');
    Route::get('/audit', AuditLogController::class)->name('audit.index');
    Route::get('/legacy/factucare', [LegacyFactucareController::class, 'index'])->name('legacy.factucare.index');
    Route::post('/legacy/factucare/search', [LegacyFactucareController::class, 'search'])->middleware('throttle:20,1')->name('legacy.factucare.search');
    Route::get('/legacy/factucare/users/{user}', [LegacyFactucareController::class, 'show'])->whereNumber('user')->name('legacy.factucare.users.show');
    Route::get('/legacy/factucare/users/{user}/conversion', [FactucareConversionController::class, 'create'])->whereNumber('user')->name('legacy.factucare.conversion.create');
    Route::post('/legacy/factucare/users/{user}/conversion', [FactucareConversionController::class, 'store'])->whereNumber('user')->name('legacy.factucare.conversion.store');
    Route::get('/legacy/factucare/conversion-plans/{plan}', [FactucareConversionController::class, 'show'])->name('legacy.factucare.conversion.plans.show');
    Route::post('/legacy/factucare/conversion-plans/{plan}/regenerate', [FactucareConversionController::class, 'regenerate'])->name('legacy.factucare.conversion.plans.regenerate');
    Route::get('/configuration', [ConfigurationController::class, 'index'])->name('configuration.index');
    Route::post('/configuration/test/{target}', [ConfigurationController::class, 'test'])->whereIn('target', ['cpanel','mysql','filesystem','factucare'])->name('configuration.test');
});
