@extends('layouts/layoutMaster')
@section('title','Preparación FC2 → iKontrol')
@section('content')
@include('admin.partials.flash')
<div class="alert alert-warning"><strong>SIMULACIÓN.</strong> No se realizarán cambios en FactuCare ni en iKontrol.</div>
<div class="d-flex justify-content-between align-items-start mb-5"><div><h4>PREPARACIÓN FC2 → IKONTROL</h4><p class="mb-0">{{ $result['source']['rfc'] }} · Usuario FC2 #{{ $result['source']['users_id'] }}</p></div><span class="badge bg-label-{{ $result['status']==='READY'?'success':($result['status']==='BLOCKED'?'danger':'warning') }} fs-6">{{ $result['status'] }}</span></div>
<div class="card mb-5"><div class="card-header"><h5 class="mb-0">Paso 1 · Configuración</h5></div><div class="card-body"><form method="GET" class="row g-4"><div class="col-md-4"><label class="form-label">Instalación destino (opcional)</label><select class="form-select" name="destination_instance_id"><option value="">Sin destino</option>@foreach($instances as $instance)<option value="{{ $instance->id }}" @selected($result['options']['destination_instance_id']===$instance->id)>{{ $instance->name }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">Uso CFDI default</label><input class="form-control" name="default_cfdi_use" value="{{ $result['options']['default_cfdi_use'] }}"></div><div class="col-md-2"><label class="form-label">ObjetoImp default</label><input class="form-control" name="default_tax_object" value="{{ $result['options']['default_tax_object'] }}"></div><div class="col-md-4"><label class="form-label">Impuesto propuesto</label><input class="form-control" value="IVA 16% · traslado fiscal" disabled></div>@foreach(['prepare_products'=>'Preparar productos fiscalmente','apply_default_tax'=>'Aplicar IVA 16% cuando FC no lo indique','force_default_tax'=>'Forzar IVA 16% a todos','preserve_series'=>'Conservar series y folios'] as $name=>$label)<div class="col-md-6"><input type="hidden" name="{{ $name }}" value="0"><label class="form-check"><input class="form-check-input" type="checkbox" name="{{ $name }}" value="1" @checked($result['options'][$name])><span class="form-check-label">{{ $label }}</span></label></div>@endforeach<div class="col-12"><button class="btn btn-primary"><i class="icon-base ti tabler-refresh me-2"></i>Paso 2 · Analizar</button></div></form></div></div>
<div class="row g-4 mb-5">@foreach(['issuer'=>'Emisor','client'=>'Clientes','product'=>'Productos','csd'=>'CSD','series'=>'Series'] as $key=>$label)@php($s=$result['summary'][$key])<div class="col-6 col-lg"><div class="card h-100"><div class="card-body"><small>{{ $label }}</small><h4>{{ $s['total'] }}</h4>@foreach($s['statuses'] as $status=>$count)<span class="badge bg-label-secondary me-1 mb-1">{{ $status }} {{ $count }}</span>@endforeach</div></div></div>@endforeach</div>
<div class="card"><div class="card-header"><ul class="nav nav-tabs card-header-tabs" role="tablist">@foreach(['summary'=>'Resumen','issuer'=>'Emisor','client'=>'Clientes','product'=>'Productos','csd'=>'CSD','series'=>'Series','history'=>'Históricos'] as $key=>$label)<li class="nav-item"><button class="nav-link @if($loop->first) active @endif" data-bs-toggle="tab" data-bs-target="#tab-{{ $key }}">{{ $label }}</button></li>@endforeach</ul></div><div class="card-body tab-content">
<div class="tab-pane fade show active" id="tab-summary"><h5>Paso 3 · Resultados</h5><p>Clientes: {{ $result['summary']['client']['total'] }} · RFC únicos: {{ $result['summary']['client_unique_rfcs'] }} · grupos duplicados: {{ $result['summary']['client_duplicate_groups'] }}</p><p>Productos: {{ $result['summary']['product']['total'] }} · claves únicas: {{ $result['summary']['product_unique_codes'] }} · grupos duplicados: {{ $result['summary']['product_duplicate_groups'] }}</p><div class="alert alert-info mb-0">El plan está listo para revisión. La ejecución se habilitará en la siguiente fase.</div></div>
@foreach(['issuer','client','product','csd','series'] as $type)<div class="tab-pane fade" id="tab-{{ $type }}"><div class="row g-3 mb-4"><div class="col-md-6"><input class="form-control plan-search" data-target="{{ $type }}" placeholder="Buscar"></div><div class="col-md-4"><select class="form-select plan-status" data-target="{{ $type }}"><option value="">Todos</option><option>READY</option><option>READY_WITH_DEFAULTS</option><option>REVIEW_REQUIRED</option><option>INVALID</option><option>INCOMPLETE</option><option>READY_TO_IMPORT</option><option>EXPIRED</option></select></div></div><div class="table-responsive"><table class="table table-hover"><thead><tr><th>Origen</th><th>Estado</th><th>Acción</th><th>Destino propuesto / advertencias</th></tr></thead><tbody>@foreach(array_filter($result['items'],fn($i)=>$i['entity_type']===$type) as $item)<tr class="plan-row plan-{{ $type }}" data-status="{{ $item['validation_status'] }}"><td>{{ $item['source_table'] }} #{{ $item['source_id'] ?? '—' }}<pre class="small mt-2 mb-0">{{ json_encode($item['preview_json']['source'] ?? [],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE) }}</pre></td><td><span class="badge bg-label-secondary">{{ $item['validation_status'] }}</span></td><td>{{ $item['proposed_action'] }}</td><td><details><summary>Origen FC → destino iKontrol</summary><pre class="small">{{ json_encode($item['preview_json']['destination'] ?? $item['preview_json'],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE) }}</pre></details>@foreach($item['warnings_json'] as $warning)<div class="text-warning small">{{ $warning }}</div>@endforeach</td></tr>@endforeach</tbody></table></div></div>@endforeach
<div class="tab-pane fade" id="tab-history"><h5>Históricos no incluidos</h5>@foreach($result['summary']['historical'] as $key=>$value)<p><strong>{{ $key }}:</strong> {{ is_numeric($value)?number_format($value):$value }}</p>@endforeach<p>Las facturas históricas, complementos y cancelaciones no serán migrados en esta fase.</p></div>
</div></div>
<form method="POST" action="{{ route('legacy.factucare.conversion.store',$result['source']['users_id']) }}" class="mt-5">@csrf @foreach($result['options'] as $key=>$value)<input type="hidden" name="{{ $key }}" value="{{ is_bool($value)?(int)$value:$value }}">@endforeach<button class="btn btn-success">Guardar plan de simulación</button></form>
@endsection
@section('page-script')<script>document.querySelectorAll('.plan-search,.plan-status').forEach(el=>el.addEventListener('input',()=>{const t=el.dataset.target,q=(document.querySelector('.plan-search[data-target="'+t+'"]')?.value||'').toLowerCase(),s=document.querySelector('.plan-status[data-target="'+t+'"]')?.value||'';document.querySelectorAll('.plan-'+t).forEach(r=>r.classList.toggle('d-none',(q&&!r.textContent.toLowerCase().includes(q))||(s&&r.dataset.status!==s)));}));</script>@endsection