@extends('layouts/layoutMaster')
@section('title', 'FactuCare '.$result['rfc'])
@section('content')
@include('admin.partials.flash')
@php
  $section = $result['section'];
  $tabs = ['summary'=>'Resumen','profile'=>'Perfil fiscal','clients'=>'Clientes','products'=>'Productos','csd'=>'CSD','folios'=>'Folios','invoices'=>'Facturas','other'=>'Otros'];
@endphp
<div class="d-flex flex-column flex-md-row justify-content-between gap-4 mb-6"><div><span class="badge bg-label-secondary mb-2">FactuCare Legacy · Solo lectura</span><h4 class="mb-1">{{ $result['rfc'] ?: 'RFC no disponible' }}</h4><p class="mb-0 text-body-secondary">{{ data_get($result, 'profile.legal_name') ?? data_get($result, 'user.name') ?? 'Nombre no disponible' }} · Usuario FC2 #{{ $result['users_id'] }}</p></div><a class="btn btn-outline-primary align-self-md-start" href="{{ route('legacy.factucare.index') }}"><i class="icon-base ti tabler-search me-2"></i>Nueva búsqueda</a></div>

<div class="card mb-6"><div class="card-header pb-0"><ul class="nav nav-tabs card-header-tabs flex-nowrap overflow-auto">@foreach($tabs as $key=>$label)<li class="nav-item"><a class="nav-link text-nowrap {{ $section===$key?'active':'' }}" href="{{ route('legacy.factucare.users.show',['user'=>$result['users_id'],'section'=>$key]) }}">{{ $label }}</a></li>@endforeach</ul></div><div class="card-body pt-6">
@if($section === 'summary')
  <div class="row g-4 mb-6">@foreach(['id'=>'ID legacy','name'=>'Nombre','email'=>'Email','active'=>'Estado / activo','created_at'=>'Fecha de creación','last_login_at'=>'Último acceso'] as $key=>$label)<div class="col-md-4"><small class="text-body-secondary d-block">{{ $label }}</small><span class="fw-medium">{{ data_get($result,"user.$key") ?? 'No disponible' }}</span></div>@endforeach</div><hr class="my-6">
  <div class="row g-4">@foreach($result['summary'] as $item)<div class="col-6 col-md-4 col-xl-3"><div class="border rounded p-4 h-100"><small class="text-body-secondary">{{ $item['label'] }}</small><h4 class="mb-0 mt-1">{{ is_numeric($item['value']) ? number_format($item['value']) : $item['value'] }}</h4></div></div>@endforeach</div>
@elseif($section === 'profile')
  <div class="row g-5">@foreach(['rfc'=>'RFC','legal_name'=>'Razón social','fiscal_regime'=>'Régimen fiscal','postal_code'=>'Código postal','street'=>'Calle','exterior_number'=>'Número exterior','interior_number'=>'Número interior','neighborhood'=>'Colonia','locality'=>'Localidad','municipality'=>'Municipio','state'=>'Estado','country'=>'País','phone'=>'Teléfono','fiscal_email'=>'Email fiscal'] as $key=>$label)<div class="col-md-6"><small class="text-body-secondary d-block">{{ $label }}</small><span class="fw-medium">{{ data_get($result,"profile.$key") ?? 'No disponible' }}</span></div>@endforeach</div>
@elseif($section === 'clients')
  @include('admin.legacy.factucare.partials.search', ['placeholder'=>'Buscar por RFC o razón social'])
  @if($result['clients'])<div class="table-responsive"><table class="table table-hover"><thead><tr><th>ID</th><th>RFC / Razón social</th><th>Contacto</th><th>Email</th><th>Teléfono</th><th>CP / Régimen</th><th>Municipio / Estado</th></tr></thead><tbody>@forelse($result['clients'] as $row)<tr><td>{{ $row->id ?? '—' }}</td><td><strong>{{ $row->rfc ?? '—' }}</strong><small class="d-block text-body-secondary">{{ $row->legal_name ?? '—' }}</small></td><td>{{ $row->contact ?? '—' }}</td><td>{{ $row->email ?? '—' }}</td><td>{{ $row->phone ?? '—' }}</td><td>{{ $row->postal_code ?? '—' }}<small class="d-block">{{ $row->fiscal_regime ?? '—' }}</small></td><td>{{ $row->municipality ?? '—' }}<small class="d-block">{{ $row->state ?? '—' }}</small></td></tr>@empty<tr><td colspan="7">Sin clientes para este usuario.</td></tr>@endforelse</tbody></table></div><div class="mt-4">{{ $result['clients']->withQueryString()->links() }}</div>@else<div class="alert alert-warning">No fue posible identificar la relación de clientes.</div>@endif
@elseif($section === 'products')
  @include('admin.legacy.factucare.partials.search', ['placeholder'=>'Buscar por clave o descripción'])
  @if($result['products'])<div class="table-responsive"><table class="table table-hover"><thead><tr><th>ID / Clave</th><th>Descripción</th><th>Precio</th><th>Unidad</th><th>ClaveProdServ SAT</th><th>ClaveUnidad SAT</th><th>Observaciones</th></tr></thead><tbody>@forelse($result['products'] as $row)<tr><td>{{ $row->id ?? '—' }}<small class="d-block">{{ $row->code ?? '—' }}</small></td><td>{{ $row->description ?? '—' }}</td><td>{{ isset($row->price)?number_format((float)$row->price,2):'—' }}</td><td>{{ $row->unit ?? '—' }}</td><td>{{ $row->sat_product_code ?? '—' }}<small class="d-block">{{ $row->sat_product_description ?? '' }}</small></td><td>{{ $row->sat_unit_code ?? '—' }}<small class="d-block">{{ $row->sat_unit_description ?? '' }}</small></td><td>{{ $row->notes ?? '—' }}</td></tr>@empty<tr><td colspan="7">Sin productos para este usuario.</td></tr>@endforelse</tbody></table></div><div class="mt-4">{{ $result['products']->withQueryString()->links() }}</div>@else<div class="alert alert-warning">No fue posible identificar la relación de productos.</div>@endif
@elseif($section === 'csd')
  @php($csd=$result['csd'])<div class="row g-4 mb-6"><div class="col-md-6"><div class="border rounded p-4"><small>Certificado CER</small><h5 class="mb-0 text-{{ $csd['has_cer']?'success':'secondary' }}">{{ $csd['has_cer']?'Sí':'No detectado' }}</h5></div></div><div class="col-md-6"><div class="border rounded p-4"><small>Llave KEY</small><h5 class="mb-0 text-{{ $csd['has_key']?'success':'secondary' }}">{{ $csd['has_key']?'Sí':'No detectada' }}</h5></div></div></div><dl class="row">@foreach(['certificate_number'=>'Número de certificado','valid_from'=>'Inicio','valid_until'=>'Vencimiento','status'=>'Estado'] as $key=>$label)<dt class="col-md-3">{{ $label }}</dt><dd class="col-md-9">{{ data_get($csd,"info.$key") ?? 'No disponible' }}</dd>@endforeach</dl>@if($csd['documents'])<div class="table-responsive"><table class="table"><thead><tr><th>Tipo</th><th>Nombre seguro</th><th>Extensión</th></tr></thead><tbody>@foreach($csd['documents'] as $document)<tr><td>{{ $document['type'] ?? '—' }}</td><td>{{ $document['filename'] ?? '—' }}</td><td>{{ $document['extension'] ?? '—' }}</td></tr>@endforeach</tbody></table></div>@endif
@elseif($section === 'folios')
  <div class="table-responsive"><table class="table"><thead><tr><th>ID</th><th>Tipo</th><th>Serie</th><th>Folio actual</th><th>Estado</th></tr></thead><tbody>@forelse($result['folios'] as $row)<tr><td>{{ $row['id'] ?? '—' }}</td><td>{{ $row['type'] ?? '—' }}</td><td>{{ $row['series'] ?? '—' }}</td><td>{{ $row['current_folio'] ?? '—' }}</td><td>{{ $row['status'] ?? '—' }}</td></tr>@empty<tr><td colspan="5">Sin folios identificados.</td></tr>@endforelse</tbody></table></div>
@elseif($section === 'invoices')
  @php($stats=$result['invoices'])<div class="row g-4 mb-6">@foreach(['total'=>'Facturas','complements'=>'Complementos','cancellations'=>'Cancelaciones'] as $key=>$label)<div class="col-md-4"><div class="border rounded p-4"><small>{{ $label }}</small><h4 class="mb-0">{{ $stats[$key]===null?'No disponible':number_format($stats[$key]) }}</h4></div></div>@endforeach</div><p>Primera fecha: <strong>{{ $stats['first_date'] ?? 'No disponible' }}</strong> · Última fecha: <strong>{{ $stats['last_date'] ?? 'No disponible' }}</strong></p>@if($stats['by_status'])<div class="table-responsive"><table class="table"><thead><tr><th>Estado</th><th>Total</th></tr></thead><tbody>@foreach($stats['by_status'] as $status=>$total)<tr><td>{{ $status }}</td><td>{{ number_format($total) }}</td></tr>@endforeach</tbody></table></div>@endif
@else
  <div class="row g-4">@forelse($result['other'] as $table=>$count)<div class="col-md-4"><div class="border rounded p-4"><small>{{ \Illuminate\Support\Str::headline($table) }}</small><h4 class="mb-0">{{ number_format($count) }}</h4></div></div>@empty<div class="col-12"><div class="alert alert-secondary">No se identificaron relaciones adicionales.</div></div>@endforelse</div>
@endif
</div></div>
<div class="alert alert-secondary"><i class="icon-base ti tabler-shield-lock me-2"></i>No se muestran passwords, tokens, API keys, contenido de certificados ni XML.</div>
@endsection
