<?php
namespace Tests\Feature;
use App\Models\{AdminUser,Client,FactucareConversionPlan,IkontrolInstance};
use App\Services\IkontrolInstanceConnectionService;
use App\Services\LegacyFc2\{FactucareConnectionService,FactucareConversionPlannerService,FactucareReaderService};
use Illuminate\Database\Events\QueryExecuted;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\{DB,Event};
use Mockery;
use Tests\TestCase;
class FactucareConversionPlannerTest extends TestCase {
 use RefreshDatabase;
 protected function setUp():void{parent::setUp();config(['fc2.connection'=>'fc2_plan','database.connections.fc2_plan'=>['driver'=>'sqlite','database'=>':memory:','prefix'=>'','foreign_key_constraints'=>true],'database.connections.plan_destination'=>['driver'=>'sqlite','database'=>':memory:','prefix'=>'','foreign_key_constraints'=>true]]);$this->sourceFixture();}
 public function test_plan_without_destination_maps_defaults_duplicates_csd_folios_and_history():void{$r=$this->planner()->plan(15);$this->assertSame('G03',$r['options']['default_cfdi_use']);$this->assertSame('02',$r['options']['default_tax_object']);$this->assertSame(2,$r['summary']['client']['total']);$this->assertSame(1,$r['summary']['client_duplicate_groups']);$this->assertSame(1,$r['summary']['product_duplicate_groups']);$this->assertSame('NOT_PLANNED',$r['summary']['historical']['strategy']);$product=collect($r['items'])->firstWhere('entity_type','product');$this->assertSame('DEFAULT',data_get($product,'preview_json.destination.tax.origin'));$this->assertSame('READY_TO_IMPORT',collect($r['items'])->firstWhere('entity_type','csd')['validation_status']);$this->assertStringNotContainsString('super-secret',json_encode($r));}
 public function test_invalid_regime_product_sat_and_expired_csd_are_classified():void{DB::connection('fc2_plan')->table('users_perfil')->update(['regimen_fiscal'=>'999']);DB::connection('fc2_plan')->table('productos')->where('id',2)->update(['clave_prod_serv_id'=>999]);DB::connection('fc2_plan')->table('users_info_factura')->update(['fecha_vencimiento'=>'2020-01-01']);$r=$this->planner()->plan(15);$this->assertContains('EXPIRED',array_column($r['items'],'validation_status'));$this->assertContains('REVIEW_REQUIRED',array_column($r['items'],'validation_status'));}
 public function test_destination_detects_client_product_series_conflicts_and_catalog_ids():void{$instance=$this->targetInstance();$this->destinationFixture();$r=$this->planner(true)->plan(15,['destination_instance_id'=>$instance->id,'preserve_series'=>true]);$this->assertTrue($r['catalog']['schema_ready']);$this->assertNotEmpty(collect($r['items'])->where('proposed_action','CONFLICT'));$p=collect($r['items'])->firstWhere('entity_type','product');$this->assertTrue(data_get($p,'preview_json.lookups.sat_product.matched'));$this->assertTrue(data_get($p,'preview_json.lookups.sat_unit.matched'));$this->assertTrue(data_get($p,'preview_json.lookups.tax.matched'));}
 public function test_fingerprint_changes_and_regeneration_is_idempotent():void{$service=$this->planner();$admin=AdminUser::create(['name'=>'Admin','email'=>'planner@test.local','password'=>'password','active'=>true]);$this->actingAs($admin);$first=$service->plan(15);$plan=$service->persist($first);$count=$plan->items()->count();$this->assertSame('SOURCE_UNCHANGED',$service->sourceState($plan));DB::connection('fc2_plan')->table('productos')->where('id',1)->update(['precio'=>101]);$this->assertSame('SOURCE_CHANGED',$service->sourceState($plan));$service->persist($service->plan(15),$plan);$this->assertSame($count,$plan->fresh()->items()->count());}
 public function test_planning_never_writes_to_source_or_destination():void{$instance=$this->targetInstance();$this->destinationFixture();$queries=[];Event::listen(QueryExecuted::class,function($e)use(&$queries){if(in_array($e->connectionName,['fc2_plan','plan_destination'],true))$queries[]=$e->sql;});$this->planner(true)->plan(15,['destination_instance_id'=>$instance->id]);$this->assertNotEmpty($queries);foreach($queries as $sql)$this->assertDoesNotMatchRegularExpression('/\b(INSERT|UPDATE|DELETE|CREATE|ALTER|DROP|TRUNCATE)\b/i',$sql);}
 public function test_ui_supports_create_save_reopen_filters_and_no_execute_action():void{$admin=AdminUser::create(['name'=>'Admin','email'=>'ui@test.local','password'=>'password','active'=>true]);$this->withoutVite();$this->app->instance(IkontrolInstanceConnectionService::class,$this->connectionMock());$this->actingAs($admin)->get('/legacy/factucare/users/15/conversion')->assertOk()->assertSee('SIMULACIÓN')->assertSee('Preparar productos fiscalmente')->assertSee('Históricos')->assertDontSee('Ejecutar migración');$this->actingAs($admin)->post('/legacy/factucare/users/15/conversion',['default_cfdi_use'=>'G03','default_tax_object'=>'02','prepare_products'=>1,'apply_default_tax'=>1])->assertRedirect();$plan=FactucareConversionPlan::firstOrFail();$this->actingAs($admin)->get(route('legacy.factucare.conversion.plans.show',$plan))->assertOk()->assertSee('SOURCE_UNCHANGED')->assertDontSee('Ejecutar migración');}
 private function planner(bool $destination=false):FactucareConversionPlannerService{return new FactucareConversionPlannerService(new FactucareReaderService(new FactucareConnectionService()),$destination?$this->connectionMock():Mockery::mock(IkontrolInstanceConnectionService::class));}
 private function connectionMock(){return Mockery::mock(IkontrolInstanceConnectionService::class)->shouldReceive('withInstanceConnection')->andReturnUsing(fn($i,$callback)=>$callback(DB::connection('plan_destination')))->getMock();}
 private function targetInstance():IkontrolInstance{$client=Client::create(['name'=>'DOLD','slug'=>'dold','active'=>true]);return IkontrolInstance::create(['client_id'=>$client->id,'name'=>'DOLD','slug'=>'dold','folder_name'=>'dold.local','db_name'=>'dold','installation_status'=>'READY','active'=>true]);}
 private function sourceFixture():void{$s=DB::connection('fc2_plan')->getSchemaBuilder();$s->create('users',fn(Blueprint $t)=>[$t->integer('id')->primary(),$t->string('nombre'),$t->string('password')->nullable()]);$s->create('users_perfil',fn(Blueprint $t)=>[$t->increments('id'),$t->integer('users_id'),$t->string('rfc'),$t->string('razon_social'),$t->string('regimen_fiscal'),$t->string('codigo_postal')]);$s->create('clientes',fn(Blueprint $t)=>[$t->increments('id'),$t->integer('users_id'),$t->string('rfc'),$t->string('razon_social'),$t->string('codigo_postal'),$t->string('regimen_fiscal')]);$s->create('clave_prod_serv',fn(Blueprint $t)=>[$t->integer('id')->primary(),$t->string('clave')]);$s->create('clave_unidad',fn(Blueprint $t)=>[$t->integer('id')->primary(),$t->string('clave')]);$s->create('productos',fn(Blueprint $t)=>[$t->increments('id'),$t->integer('users_id'),$t->string('clave'),$t->string('descripcion'),$t->decimal('precio',12,2),$t->integer('clave_prod_serv_id'),$t->integer('clave_unidad_id')]);$s->create('users_info_factura',fn(Blueprint $t)=>[$t->increments('id'),$t->integer('users_id'),$t->string('numero_certificado'),$t->date('fecha_inicio'),$t->date('fecha_vencimiento'),$t->text('cer'),$t->text('key'),$t->string('password_key')]);foreach(['folios','facturas','complementos','cancelaciones'] as $name)$s->create($name,function(Blueprint $t)use($name){$t->increments('id');$t->integer('users_id');if($name==='folios'){$t->string('tipo');$t->string('serie');$t->integer('folio');}});$db=DB::connection('fc2_plan');$db->table('users')->insert(['id'=>15,'nombre'=>'DOLD','password'=>'super-secret']);$db->table('users_perfil')->insert(['users_id'=>15,'rfc'=>'DOLD860620EW7','razon_social'=>'DOLD SA','regimen_fiscal'=>'612','codigo_postal'=>'77500']);$db->table('clientes')->insert([['users_id'=>15,'rfc'=>'AAA010101AAA','razon_social'=>'Cliente A','codigo_postal'=>'77500','regimen_fiscal'=>'612'],['users_id'=>15,'rfc'=>'AAA010101AAA','razon_social'=>'Cliente A duplicado','codigo_postal'=>'77500','regimen_fiscal'=>'612']]);$db->table('clave_prod_serv')->insert(['id'=>1,'clave'=>'60122300']);$db->table('clave_unidad')->insert(['id'=>1,'clave'=>'H87']);$db->table('productos')->insert([['users_id'=>15,'clave'=>'ZAP','descripcion'=>'Zapatos','precio'=>100,'clave_prod_serv_id'=>1,'clave_unidad_id'=>1],['users_id'=>15,'clave'=>'ZAP','descripcion'=>'Zapatos 2','precio'=>120,'clave_prod_serv_id'=>1,'clave_unidad_id'=>1]]);$db->table('users_info_factura')->insert(['users_id'=>15,'numero_certificado'=>'30001','fecha_inicio'=>'2025-01-01','fecha_vencimiento'=>'2030-01-01','cer'=>'binary','key'=>'binary','password_key'=>'super-secret']);$db->table('folios')->insert(['users_id'=>15,'tipo'=>'I','serie'=>'A','folio'=>10]);$db->table('facturas')->insert(['users_id'=>15]);$db->table('complementos')->insert(['users_id'=>15]);$db->table('cancelaciones')->insert(['users_id'=>15]);}
 private function destinationFixture():void{$s=DB::connection('plan_destination')->getSchemaBuilder();foreach(['ikontrol_sat_tax_regimes'=>['612'],'ikontrol_sat_cfdi_uses'=>['G03'],'ikontrol_sat_product_service_keys'=>['60122300'],'ikontrol_sat_unit_keys'=>['H87'],'ikontrol_sat_tax_object_codes'=>['02']] as $table=>$codes){$s->create($table,fn(Blueprint $t)=>[$t->increments('id'),$t->string('code')]);DB::connection('plan_destination')->table($table)->insert(['code'=>$codes[0]]);}$s->create('ikontrol_clients',fn(Blueprint $t)=>[$t->increments('id'),$t->string('vat_number')]);$s->create('ikontrol_items',fn(Blueprint $t)=>[$t->increments('id'),$t->string('identification_number')]);$s->create('ikontrol_fiscal_series',fn(Blueprint $t)=>[$t->increments('id'),$t->string('document_type'),$t->string('series')]);$s->create('ikontrol_taxes',fn(Blueprint $t)=>[$t->increments('id'),$t->string('title'),$t->decimal('percentage'),$t->string('fiscal_tax_type'),$t->boolean('use_for_fiscal')]);$db=DB::connection('plan_destination');$db->table('ikontrol_clients')->insert(['vat_number'=>'AAA010101AAA']);$db->table('ikontrol_items')->insert(['identification_number'=>'ZAP']);$db->table('ikontrol_fiscal_series')->insert(['document_type'=>'I','series'=>'A']);$db->table('ikontrol_taxes')->insert(['title'=>'IVA','percentage'=>16,'fiscal_tax_type'=>'transfer','use_for_fiscal'=>1]);}
}