<?php
namespace Tests\Feature;
use App\Enums\InstallationStatus;use App\Models\{Client,IkontrolInstance,IkontrolTemplate};use App\Services\{AllowedSparkRunner,AuditService,CpanelService,IkontrolDeploymentService,IkontrolInstanceConnectionService,IkontrolInstanceOperationsService,InstanceFilesystemService,InstanceProvisioningService};use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Support\Facades\File;use Mockery;use RuntimeException;use Tests\TestCase;
class InstanceOperationsTest extends TestCase{
 use RefreshDatabase;private string$root;
 protected function setUp():void{parent::setUp();$this->root=storage_path('framework/testing/operations-'.uniqid());File::ensureDirectoryExists($this->root);config(['ikontrol.instances_root'=>$this->root,'ikontrol.folder_suffix'=>'.ikontrol.solutions','ikontrol.db.prefix'=>'test_']);}
 protected function tearDown():void{File::deleteDirectory($this->root);parent::tearDown();}
 public function test_file_verification_is_safe_and_audited():void{$i=$this->makeInstance();foreach(['app','system','writable']as$d)File::ensureDirectoryExists($i->absolute_path.'/'.$d);foreach(['index.php','spark','.env']as$f)File::put($i->absolute_path.'/'.$f,'x');$result=$this->service()->verifyFiles($i);$this->assertSame('READY',$result['status']);$this->assertDatabaseHas('admin_audit_logs',['action'=>'verify_instance_files']);}
 public function test_ready_is_protected_from_restart():void{$i=$this->makeInstance('prod',['name'=>'Productiva','installation_status'=>InstallationStatus::Ready]);$this->expectException(RuntimeException::class);$this->service()->restart($i,$i->slug);}
 public function test_dold_is_protected_from_restart():void{$i=$this->makeInstance('dold',['name'=>'DOLD','installation_status'=>InstallationStatus::Failed]);$this->expectException(RuntimeException::class);$this->service()->restart($i,$i->slug);}
 public function test_database_prefix_is_enforced_before_cpanel():void{$i=$this->makeInstance('unsafe',['db_name'=>'foreign_database']);$cp=Mockery::mock(CpanelService::class);$cp->shouldNotReceive('assignUserToDatabase');$this->expectException(RuntimeException::class);$this->service($cp)->reassignDatabaseUser($i);}
 public function test_sensitive_password_is_not_persisted():void{$i=$this->makeInstance();$secret='HighlySecret123!';$deployment=Mockery::mock(IkontrolDeploymentService::class);$deployment->shouldReceive('runSensitiveTemplateCommand')->once()->with($i,'ikontrol:admin-provision',['Carlos','admin@example.test'],$secret)->andReturn(['exit_code'=>0,'duration_ms'=>2]);$this->service(null,$deployment)->provisionAdmin($i,'Carlos','admin@example.test',$secret);$this->assertStringNotContainsString($secret,json_encode(\Illuminate\Support\Facades\DB::table('admin_audit_logs')->get()));$this->assertStringNotContainsString($secret,json_encode(\Illuminate\Support\Facades\DB::table('instance_installation_logs')->get()));}
 public function test_spark_runner_rejects_arbitrary_command():void{$this->expectException(RuntimeException::class);(new AllowedSparkRunner)->run($this->root,'db:query',['DROP TABLE users']);}
 public function test_diagnostic_runner_rejects_arbitrary_command():void{$this->expectException(RuntimeException::class);(new AllowedSparkRunner)->runDiagnostic($this->root,'spark:anything','admin@example.test');}
 public function test_health_does_not_claim_total_healthy_without_authenticated_checks():void{$i=$this->makeInstance();foreach(['app','system','writable']as$d)File::ensureDirectoryExists($i->absolute_path.'/'.$d);foreach(['index.php','spark','.env']as$f)File::put($i->absolute_path.'/'.$f,'x');$d=Mockery::mock(IkontrolDeploymentService::class);$d->shouldReceive('installOperationalCommandsFor')->once();$d->shouldReceive('runTemplateCommand')->with($i,'ikontrol:database-check',[])->andReturn(['exit_code'=>0,'duration_ms'=>1]);$c=Mockery::mock(IkontrolInstanceConnectionService::class);$c->shouldReceive('test')->once()->andReturn(['success'=>true,'status'=>'CONNECTED']);\Illuminate\Support\Facades\Http::fake(['*'=>\Illuminate\Support\Facades\Http::response('',200)]);$s=new IkontrolInstanceOperationsService($d,$c,Mockery::mock(CpanelService::class),app(AuditService::class),app(InstanceFilesystemService::class),Mockery::mock(InstanceProvisioningService::class));$result=$s->health($i);$this->assertSame('APPLICATION_READY',$result['status']);$this->assertSame('NOT_CHECKED',$result['administrator']);$this->assertNotSame('HEALTHY',$result['status']);}
 private function makeInstance(string$slug='testop',array$extra=[]):IkontrolInstance{$client=Client::create(['name'=>'Test','active'=>true]);$template=IkontrolTemplate::create(['version'=>uniqid(),'name'=>'Base','app_version'=>'2','schema_version'=>'1','archive_path'=>'a.zip','database_dump_path'=>'a.sql','archive_sha256'=>str_repeat('a',64),'database_sha256'=>str_repeat('b',64),'active'=>true]);$path=$this->root.'/'.$slug.'.ikontrol.solutions';File::ensureDirectoryExists($path);return IkontrolInstance::create(array_merge(['client_id'=>$client->id,'ikontrol_template_id'=>$template->id,'name'=>'Prueba','slug'=>$slug,'folder_name'=>$slug.'.ikontrol.solutions','absolute_path'=>$path,'db_name'=>'test_'.$slug,'installation_status'=>InstallationStatus::Failed,'is_test'=>true],$extra));}
 private function service(?CpanelService$cp=null,?IkontrolDeploymentService$d=null):IkontrolInstanceOperationsService{return new IkontrolInstanceOperationsService($d??Mockery::mock(IkontrolDeploymentService::class),Mockery::mock(IkontrolInstanceConnectionService::class),$cp??Mockery::mock(CpanelService::class),app(AuditService::class),app(InstanceFilesystemService::class),Mockery::mock(InstanceProvisioningService::class));}
}
