<?php
namespace Tests\Feature;
use App\Enums\InstallationStatus;use App\Models\{Client,IkontrolInstance,IkontrolTemplate};use App\Services\{AuditService,IkontrolDeploymentService,IkontrolStampService,InstanceLogService};use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Support\Facades\File;use Mockery;use RuntimeException;use Tests\TestCase;
class InstanceDiagnosticsTest extends TestCase{
 use RefreshDatabase;private string$root;private IkontrolInstance$i;
 protected function setUp():void{parent::setUp();$this->root=storage_path('framework/testing/diagnostics-'.uniqid());config(['ikontrol.instances_root'=>$this->root,'ikontrol.folder_suffix'=>'.ikontrol.solutions']);$client=Client::create(['name'=>'Test','active'=>true]);$t=IkontrolTemplate::create(['version'=>uniqid(),'name'=>'Base','app_version'=>'2','schema_version'=>'1','archive_path'=>'a','database_dump_path'=>'b','archive_sha256'=>str_repeat('a',64),'database_sha256'=>str_repeat('b',64),'active'=>true]);$path=$this->root.'/demo.ikontrol.solutions';File::ensureDirectoryExists($path.'/writable/logs');$this->i=IkontrolInstance::create(['client_id'=>$client->id,'ikontrol_template_id'=>$t->id,'name'=>'Demo','slug'=>'demo','folder_name'=>'demo.ikontrol.solutions','absolute_path'=>$path,'db_name'=>'test_demo','installation_status'=>InstallationStatus::Failed]);}
 protected function tearDown():void{File::deleteDirectory($this->root);parent::tearDown();}
 public function test_logs_are_listed_newest_first_and_empty_is_safe():void{$s=$this->logs();$this->assertSame([],$s->listing($this->i));File::put($this->path('old.log'),'a');touch($this->path('old.log'),100);File::put($this->path('new.log'),'b');touch($this->path('new.log'),200);$this->assertSame(['new.log','old.log'],array_column($s->listing($this->i),'name'));}
 public function test_log_read_redacts_secrets_and_limits_lines():void{$rows=[];for($n=1;$n<=1200;$n++)$rows[]="line {$n}";$rows[]='password: abc token=xyz Authorization: Bearer tokenvalue';File::put($this->path('app.log'),implode("\n",$rows));$r=$this->logs()->read($this->i,'app.log',100);$this->assertLessThanOrEqual(100,substr_count($r['content'],"\n")+1);$this->assertStringNotContainsString('abc',$r['content']);$this->assertStringNotContainsString('xyz',$r['content']);$this->assertStringNotContainsString('tokenvalue',$r['content']);}
 public function test_invalid_missing_and_traversal_logs_are_rejected():void{foreach(['../app.log','missing.log','index.html']as$name){try{$this->logs()->read($this->i,$name);$this->fail('Debió rechazarse.');}catch(RuntimeException){$this->addToAssertionCount(1);}}}
 public function test_log_search_is_bounded_php_filter():void{File::put($this->path('app.log'),"INFO ok\nERROR DatabaseException\nERROR Other");$r=$this->logs()->read($this->i,'app.log',100,'DatabaseException');$this->assertStringContainsString('DatabaseException',$r['content']);$this->assertStringNotContainsString('Other',$r['content']);}
 public function test_stamp_status_and_credit_use_controlled_contract_and_audit():void{$d=Mockery::mock(IkontrolDeploymentService::class);$d->shouldReceive('installOperationalCommandsFor')->once();$d->shouldReceive('runTemplateCommand')->with($this->i,'ikontrol:stamps-status',[])->andReturn(['exit_code'=>0,'output'=>'{"status":"SUCCESS","balance":10,"credited":12,"consumed":2}']);$d->shouldReceive('runStampMovement')->once()->withArgs(fn($i,$a,$q,$reason,$id)=>$i->is($this->i)&&$a==='credit'&&$q===5&&$reason==='Compra'&&strlen($id)===32)->andReturn(['exit_code'=>0,'output'=>'{"status":"SUCCESS","available_after":15}']);$s=new IkontrolStampService($d,app(AuditService::class));$this->assertSame(10,$s->status($this->i)['balance']);$this->assertSame(15,$s->move($this->i,'credit',5,'Compra')['available_after']);$this->assertDatabaseHas('admin_audit_logs',['action'=>'instance_stamps_credit']);}
 public function test_invalid_stamp_quantity_never_runs_command():void{$d=Mockery::mock(IkontrolDeploymentService::class);$d->shouldNotReceive('runStampMovement');$this->expectException(RuntimeException::class);(new IkontrolStampService($d,app(AuditService::class)))->move($this->i,'debit',0,'X');}
 public function test_logs_clear_uses_only_allowlisted_command_and_audits():void{$d=Mockery::mock(IkontrolDeploymentService::class);$d->shouldReceive('runTemplateCommand')->once()->with($this->i,'logs:clear',['--force'])->andReturn(['exit_code'=>0]);(new InstanceLogService(app(AuditService::class),$d))->clear($this->i);$this->assertDatabaseHas('admin_audit_logs',['action'=>'clear_instance_logs']);}
 public function test_debit_uses_positive_quantity_and_audits():void{$d=Mockery::mock(IkontrolDeploymentService::class);$d->shouldReceive('runStampMovement')->once()->withArgs(fn($i,$a,$q)=>$a==='debit'&&$q===3)->andReturn(['exit_code'=>0,'output'=>'{"status":"SUCCESS","available_after":7}']);$r=(new IkontrolStampService($d,app(AuditService::class)))->move($this->i,'debit',3,'Ajuste');$this->assertSame(7,$r['available_after']);$this->assertDatabaseHas('admin_audit_logs',['action'=>'instance_stamps_debit']);}
 public function test_insufficient_balance_is_sanitized():void{$d=Mockery::mock(IkontrolDeploymentService::class);$d->shouldReceive('runStampMovement')->andReturn(['exit_code'=>1,'output'=>'Insufficient fiscal stamp balance password=secret']);$this->expectExceptionMessage('Saldo de timbres insuficiente.');(new IkontrolStampService($d,app(AuditService::class)))->move($this->i,'debit',99,'Ajuste');}
 private function logs():InstanceLogService{return new InstanceLogService(app(AuditService::class),Mockery::mock(IkontrolDeploymentService::class));}
 private function path(string$name):string{return$this->i->absolute_path.'/writable/logs/'.$name;}
}
