<?php

return [
    'db' => [
        'host' => env('IKONTROL_DB_HOST', 'localhost'),
        'port' => (int) env('IKONTROL_DB_PORT', 3306),
        'username' => env('IKONTROL_DB_USERNAME'),
        'password' => env('IKONTROL_DB_PASSWORD'),
        'prefix' => env('IKONTROL_DB_PREFIX', 'tws001_ik_'),
        'table_prefix' => env('IKONTROL_DB_TABLE_PREFIX', 'ikontrol_'),
    ],
    'instances_root' => env('IKONTROL_INSTANCES_ROOT', '/home/tws001'),
    'folder_suffix' => env('IKONTROL_FOLDER_SUFFIX', '.ikontrol.solutions'),
    'version_sources' => [
        'archive_root' => env('IKONTROL_VERSION_ARCHIVE_ROOT', storage_path('ikontrol-versions')),
        'manifest_root' => env('IKONTROL_VERSION_MANIFEST_ROOT', storage_path('ikontrol-versions')),
        'default_target' => env('IKONTROL_UPGRADE_TARGET', '2.0.0'),
    ],
    'templates' => [
        'root' => env('IKONTROL_TEMPLATE_ROOT', storage_path('ikontrol-templates')),
        'mysql_binary' => env('IKONTROL_MYSQL_BINARY', 'mysql'),
        'table_classification' => [
            'structure_only' => [],
            'keep_data' => [],
            'empty_data' => [],
        ],
    ],
    'deployment' => [
        'command_timeout' => (int) env('IKONTROL_DEPLOYMENT_TIMEOUT', 300),
        'php_binary' => env('IKONTROL_PHP_BINARY', PHP_BINARY),
        'diagnostic_tools_version' => '1.3.0',
        'settings_baseline' => [
          'base_required' => [
            'timezone' => 'America/Mexico_City',
            'language' => 'spanish',
            'date_format' => 'Y-m-d',
            'time_format' => 'small',
            'first_day_of_week' => '0',
            'weekends' => '',
            'default_currency' => 'MXN',
            'currency_symbol' => '$',
            'currency_position' => 'left',
            'decimal_separator' => '.',
            'no_of_decimals' => '2',
            'accepted_file_formats' => 'jpg,jpeg,png,doc,xlsx,txt,pdf,zip,webm',
          ],
          'module_default' => [
            'module_announcement'=>'1','module_attendance'=>'1','module_chat'=>'1',
            'module_contract'=>'','module_estimate'=>'1','module_estimate_request'=>'',
            'module_event'=>'1','module_expense'=>'1','module_file_manager'=>'1',
            'module_gantt'=>'1','module_help'=>'1','module_invoice'=>'1',
            'module_knowledge_base'=>'1','module_lead'=>'1','module_leave'=>'1',
            'module_message'=>'1','module_note'=>'1','module_order'=>'',
            'module_project_timesheet'=>'1','module_proposal'=>'1','module_reminder'=>'1',
            'module_subscription'=>'','module_ticket'=>'','module_timeline'=>'1','module_todo'=>'1',
          ],
          'optional_general' => [
            'add_signature_option_on_accepting_estimate'=>'1','add_signature_option_on_accepting_proposal'=>'1',
            'allowed_ip_addresses'=>'','contract_color'=>'#000000','conversion_rate'=>'a:0:{}',
            'create_new_invoices_automatically_when_estimates_gets_accepted'=>'1',
            'default_contract_template'=>'1','default_due_date_after_billing_date'=>'14',
            'default_permissions_for_non_primary_contact'=>'projects','default_proposal_template'=>'3',
            'disable_proposal_pdf_for_clients'=>'','email_protocol'=>'mail','enable_audio_recording'=>'1',
            'enable_background_image_for_invoice_pdf'=>'','enable_comments_on_estimates'=>'',
            'enable_comments_on_proposals'=>'','enable_estimate_lock_state'=>'1','enable_invoice_id_editing'=>'',
            'enable_proposal_lock_state'=>'1','initial_number_of_the_estimate'=>'1',
            'initial_number_of_the_invoice'=>'1','initial_number_of_the_proposal'=>'1',
            'invoice_item_list_background'=>'#f4f4f4','invoice_number_format'=>'{SERIAL}',
            'invoice_style'=>'style_1','reset_invoice_number_every_year'=>'',
            'set_invoice_pdf_background_only_on_first_page'=>'','show_background_image_in_signin_page'=>'',
            'show_logo_in_signin_page'=>'yes','show_most_recent_estimate_comments_at_the_top'=>'',
            'show_most_recent_proposal_comments_at_the_top'=>'','show_the_status_checkbox_in_tasks_list'=>'1',
            'show_theme_color_changer'=>'yes','smtp_authorized'=>'0','task_point_range'=>'5','year_based_on'=>'bill_date',
          ],
          'customer_specific' => [
            'app_title'=>'iKontrol','default_theme_color'=>'2e86c1','landing_page'=>'',
            'site_logo' => '',
            'favicon' => '',
            'signin_page_background'=>'','invoice_logo'=>'','invoice_prefix'=>'','invoice_footer'=>'',
            'invoice_color'=>'#000000','estimate_prefix'=>'','estimate_footer'=>'','estimate_color'=>'#000000',
            'proposal_prefix'=>'','proposal_color'=>'#000000','order_color'=>'#000000',
            'email_sent_from_address'=>'','email_sent_from_name'=>'','email_smtp_host'=>'',
            'email_smtp_port'=>'','email_smtp_security_type'=>'none','email_smtp_user'=>'',
            'item_purchase_code' => 'CLEAN-LOCAL-NOT-LICENSED',
          ],
        ],
        'settings_secret_keys' => ['email_smtp_pass','gmail_smtp_client_id','gmail_smtp_client_secret','outlook_smtp_client_id','outlook_smtp_client_secret'],
        // Contracts are keyed by the template schema_version. Undefined schemas are reported, never guessed.
        'schema_tables' => [
            'rise-administrative-baseline-1' => ['users', 'roles', 'team', 'settings', 'dashboards', 'custom_widgets'],
        ],
    ],
    'cpanel' => [
        'host' => env('CPANEL_HOST'),
        'port' => (int) env('CPANEL_PORT', 2083),
        'username' => env('CPANEL_USERNAME'),
        'token' => env('CPANEL_API_TOKEN'),
    ],
];
