<?php
namespace App\Services\Upgrade;
use App\Models\IkontrolInstance;
final class InstanceVersionDetectorService {
 public function detect(IkontrolInstance $instance):array{$root=rtrim((string)$instance->absolute_path,'/\\');$signals=[];$framework=null;$frameworkVersion=null;$rise=null;$ikontrol=null;
  $composer=$this->json($root.DIRECTORY_SEPARATOR.'composer.json');$lock=$this->json($root.DIRECTORY_SEPARATOR.'composer.lock');foreach($lock['packages']??[] as $package){$name=$package['name']??'';if($name==='codeigniter4/framework'){$framework='CodeIgniter';$frameworkVersion=ltrim((string)($package['version']??''),'v');$signals[]=['source'=>'composer.lock','signal'=>'codeigniter4/framework','value'=>$frameworkVersion];}}
  if(!$framework&&isset($composer['require']['codeigniter4/framework'])){$framework='CodeIgniter';$frameworkVersion=(string)$composer['require']['codeigniter4/framework'];$signals[]=['source'=>'composer.json','signal'=>'codeigniter4/framework','value'=>$frameworkVersion];}
  foreach(['app/Config/App.php','system/CodeIgniter.php','spark'] as $relative)if(is_file($root.DIRECTORY_SEPARATOR.str_replace('/',DIRECTORY_SEPARATOR,$relative)))$signals[]=['source'=>'filesystem','signal'=>$relative,'value'=>'PRESENT'];
  foreach(['version.json','app/version.json','app/Config/Version.php'] as $relative){$path=$root.DIRECTORY_SEPARATOR.str_replace('/',DIRECTORY_SEPARATOR,$relative);if(!is_file($path))continue;$body=(string)file_get_contents($path);if(preg_match('/(?:ikontrol[^0-9]{0,20})?([0-9]+\.[0-9]+(?:\.[0-9]+)?)/i',$body,$m)){$ikontrol=$m[1];$signals[]=['source'=>$relative,'signal'=>'ikontrol_version','value'=>$ikontrol];}}
  foreach(['RISE_VERSION','app_version','rise_version'] as $needle){foreach(['app/Config/App.php','app/Config/Constants.php'] as $relative){$path=$root.DIRECTORY_SEPARATOR.str_replace('/',DIRECTORY_SEPARATOR,$relative);$body=is_file($path)?(string)file_get_contents($path):'';if(preg_match('/'.preg_quote($needle,'/').'[^0-9]{0,30}([0-9]+\.[0-9]+(?:\.[0-9]+)?)/i',$body,$m)){$rise=$m[1];$signals[]=['source'=>$relative,'signal'=>'rise_version','value'=>$rise];break 2;}}}
  $fiscalFiles=['app/Config/Fiscal.php','app/Config/TimbradorXpress.php','app/Services/FiscalService.php'];$fiscal=array_values(array_filter($fiscalFiles,fn($f)=>is_file($root.DIRECTORY_SEPARATOR.str_replace('/',DIRECTORY_SEPARATOR,$f))));$known=(bool)($ikontrol||$rise);$confidence=$ikontrol&&$framework?'HIGH':(($known||$framework)?'MEDIUM':'LOW');
  return['framework'=>$framework,'framework_version'=>$frameworkVersion,'rise_version'=>$rise,'ikontrol_version'=>$ikontrol,'detected_version'=>$ikontrol?"iKontrol {$ikontrol}":($rise?"Rise {$rise}":'LEGACY_UNKNOWN'),'fiscal'=>(bool)$fiscal,'confidence'=>$confidence,'signals'=>$signals,'modules'=>$this->directories($root.DIRECTORY_SEPARATOR.'app'.DIRECTORY_SEPARATOR.'Modules'),'commands'=>is_file($root.DIRECTORY_SEPARATOR.'spark')?['spark'=>'PRESENT']:[]]; }
 private function json(string $path):array{if(!is_file($path))return[];try{return json_decode((string)file_get_contents($path),true,512,JSON_THROW_ON_ERROR)?:[];}catch(\Throwable){return[];}}
 private function directories(string $path):array{if(!is_dir($path))return[];$out=[];foreach(new \DirectoryIterator($path)as$f)if($f->isDir()&&!$f->isDot())$out[]=$f->getFilename();sort($out);return$out;}
}
