<?php
namespace App\Services\Upgrade;
use App\Models\{IkontrolInstance,IkontrolUpgradeAudit}; use App\Services\IkontrolInstanceConnectionService; use Throwable;
final class InstanceUpgradeAuditService {
 public function __construct(private InstanceVersionDetectorService$detector,private InstanceDatabaseUpgradeAuditor$database,private InstanceSettingsUpgradeAuditor$settings,private InstanceFilesUpgradeAuditor$files,private InstanceFiscalCapabilityAuditor$fiscal,private InstanceUpgradeCompatibilityService$compatibility,private InstanceUpgradePlanService$plan,private IkontrolInstanceConnectionService$connections){}
 public function audit(IkontrolInstance$instance,string$target):IkontrolUpgradeAudit{
  $definition=IkontrolVersionDefinition::load($target);$audit=IkontrolUpgradeAudit::create(['ikontrol_instance_id'=>$instance->id,'target_version'=>$target,'status'=>'AUDITING','started_at'=>now()]);$instance->update(['target_version'=>$target,'upgrade_status'=>'AUDITING']);
  try{$detection=$this->detector->detect($instance);$items=array_merge($this->files->audit($instance,$definition),$this->detectedItems($detection,$definition));
   $remote=$this->connections->withInstanceConnection($instance,function($db)use($instance,$definition){$result=[];foreach([fn()=>$this->database->audit($instance,$definition,$db),fn()=>$this->settings->audit($definition,$db),fn()=>$this->fiscal->audit($instance,$definition,$db)]as$run){try{$result=array_merge($result,$run());}catch(Throwable$e){$result[]=UpgradeAuditItem::make('ENVIRONMENT','AUDITOR','remote-read','UNKNOWN','CRITICAL',null,null,['difference'=>'READ_FAILED','message'=>$e->getMessage()]);}}return$result;});
   $items=array_merge($items,$remote);$decision=$this->compatibility->evaluate($detection,$items,$definition);$plan=$this->plan->generate($detection,$definition,$items,$decision);foreach($items as$item)$audit->items()->create($item);$audit->update(['source_version'=>$detection['detected_version'],'status'=>'AUDITED','compatibility'=>$decision['compatibility'],'finished_at'=>now(),'summary_json'=>['detection'=>$detection,'compatibility'=>$decision,'counts'=>$plan['categories']],'plan_json'=>$plan]);$instance->update(['detected_version'=>$detection['detected_version'],'target_version'=>$target,'upgrade_status'=>$decision['compatibility'],'last_upgrade_audit_at'=>now()]);return$audit->fresh('items');
  }catch(Throwable$e){$audit->update(['status'=>'FAILED','finished_at'=>now(),'summary_json'=>['error'=>'No fue posible completar la auditoría.']]);$instance->update(['upgrade_status'=>'MANUAL_REVIEW','last_upgrade_audit_at'=>now()]);throw$e;}
 }
 public function regeneratePlan(IkontrolUpgradeAudit$audit):array{$definition=IkontrolVersionDefinition::load($audit->target_version);$items=$audit->items->map->only(['category','object_type','object_name','status','severity','current_value','expected_value','details_json'])->all();$detection=$audit->summary_json['detection']??['detected_version'=>$audit->source_version];$decision=$this->compatibility->evaluate($detection,$items,$definition);$plan=$this->plan->generate($detection,$definition,$items,$decision);$audit->update(['plan_json'=>$plan]);return$plan;}
 private function detectedItems(array$d,IkontrolVersionDefinition$v):array{$items=[];$expected=$v->manifest['framework']??null;$actual=trim(($d['framework']??'').' '.($d['framework_version']??''));$items[]=UpgradeAuditItem::make('FRAMEWORK','FRAMEWORK','application',$actual&&(!$expected||str_contains($expected,$actual))?'OK':'UNKNOWN',$actual?'INFO':'WARNING',$actual?:null,$expected,['confidence'=>$d['confidence']??'LOW']);foreach($v->manifest['required_modules']??[]as$name)$items[]=UpgradeAuditItem::make('MODULES','MODULE',$name,in_array($name,$d['modules']??[],true)?'OK':'MISSING','WARNING');foreach($v->manifest['required_commands']??[]as$name)$items[]=UpgradeAuditItem::make('COMMANDS','COMMAND',$name,array_key_exists($name,$d['commands']??[])?'OK':'MISSING','WARNING');return$items;}
}
