<?php
namespace App\Services\Upgrade;
use App\Models\IkontrolInstance; use Illuminate\Database\ConnectionInterface;
final class InstanceDatabaseUpgradeAuditor {
 public function audit(IkontrolInstance $instance,IkontrolVersionDefinition $definition,ConnectionInterface $db):array{$items=[];$schema=$instance->db_name;$tables=collect($db->select('SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = ?',[$schema]))->mapWithKeys(fn($r)=>[(string)$r->TABLE_NAME=>true]);
  foreach($definition->database['tables']??[] as $table){$name=$table['name'];if(!$tables->has($name)){$items[]=UpgradeAuditItem::make('DATABASE','TABLE',$name,'MISSING',$table['severity']??'WARNING',null,'required',['difference'=>'TABLE_MISSING']);continue;}$columns=collect($db->select('SELECT COLUMN_NAME, COLUMN_TYPE, IS_NULLABLE, COLUMN_DEFAULT FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = ? AND TABLE_NAME = ?',[$schema,$name]))->keyBy(fn($r)=>(string)$r->COLUMN_NAME);
   foreach($table['columns']??[] as $expected){$col=$columns->get($expected['name']);if(!$col){$items[]=UpgradeAuditItem::make('DATABASE','COLUMN',"{$name}.{$expected['name']}",'MISSING',$expected['severity']??'WARNING',null,$expected,['difference'=>'COLUMN_MISSING']);continue;}$actual=['type'=>strtolower($col->COLUMN_TYPE),'nullable'=>$col->IS_NULLABLE==='YES','default'=>$col->COLUMN_DEFAULT];$typeOk=$this->typeMatches($actual['type'],strtolower($expected['type']));if(!$typeOk){$items[]=UpgradeAuditItem::make('DATABASE','COLUMN',"{$name}.{$expected['name']}",'INCOMPATIBLE','CRITICAL',$actual,$expected,['difference'=>'COLUMN_TYPE_DIFFERENT','requires_data_review'=>true]);}elseif(isset($expected['nullable'])&&$actual['nullable']!==$expected['nullable'])$items[]=UpgradeAuditItem::make('DATABASE','COLUMN',"{$name}.{$expected['name']}",'DIFFERENT','WARNING',$actual,$expected,['difference'=>'COLUMN_NULLABILITY_DIFFERENT']);else $items[]=UpgradeAuditItem::make('DATABASE','COLUMN',"{$name}.{$expected['name']}",'OK','INFO',$actual,$expected);}
   $indexes=collect($db->select('SELECT INDEX_NAME, COLUMN_NAME, NON_UNIQUE FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = ? AND TABLE_NAME = ? ORDER BY SEQ_IN_INDEX',[$schema,$name]))->groupBy(fn($r)=>(string)$r->INDEX_NAME);foreach($table['indexes']??[]as$expected){$idx=$indexes->get($expected['name']);if(!$idx)$items[]=UpgradeAuditItem::make('DATABASE','INDEX',"{$name}.{$expected['name']}",'MISSING',$expected['severity']??'WARNING',null,$expected,['difference'=>'INDEX_MISSING']);else $items[]=UpgradeAuditItem::make('DATABASE','INDEX',"{$name}.{$expected['name']}",'OK');}
  }return$items; }
 private function typeMatches(string $actual,string $expected):bool{return$actual===$expected||preg_replace('/\s+/','',$actual)===preg_replace('/\s+/','',$expected);}
}
