@extends('layouts/contentNavbarLayout')
@section('title','Plan de despliegue')
@section('content')
@php($plan=$updateRun->deployment_plan??[])
<div class="d-flex justify-content-between align-items-center mb-6"><div><h4 class="mb-1">Plan de despliegue</h4><p class="mb-0">{{ $instance->domain }} · {{ $updateRun->from_version ?? 'legacy' }} → {{ $updateRun->to_version }}</p></div><a class="btn btn-outline-secondary" href="{{ route('instances.show',[$instance,'tab'=>'upgrade']) }}">Volver</a></div>
<div class="card mb-6"><div class="card-body"><div class="row g-4"><div class="col-md-3"><small>Estado</small><div><strong>{{ $updateRun->status }}</strong></div></div><div class="col-md-3"><small>Release</small><div>{{ $updateRun->release?->release_identifier ?? $updateRun->release?->version }}</div></div><div class="col-md-3"><small>Commit</small><div><code>{{ $updateRun->release?->commit_sha }}</code></div></div><div class="col-md-3"><small>DB preflight</small><div>{{ $plan['database_preflight']??'UNKNOWN' }}</div></div><div class="col-md-3"><small>Nuevos</small><div>{{ count($plan['files_to_create']??[]) }}</div></div><div class="col-md-3"><small>Reemplazados</small><div>{{ count($plan['files_to_replace']??[]) }}</div></div><div class="col-md-3"><small>Conflictos</small><div>{{ count($plan['local_conflicts']??[]) }}</div></div><div class="col-md-3"><small>Protegidos</small><div>{{ count($plan['protected_files']??[]) }}</div></div><div class="col-md-3"><small>Espacio requerido</small><div>{{ number_format(($plan['required_disk_space']??0)/1048576,1) }} MB</div></div></div></div></div>
@if($plan['local_conflicts']??[])<div class="alert alert-danger"><strong>Conflictos locales:</strong><ul class="mb-0">@foreach($plan['local_conflicts'] as $conflict)<li><code>{{ $conflict['path'] }}</code> — {{ $conflict['reason'] }}</li>@endforeach</ul></div>@endif
@if($updateRun->status==='DEPLOYMENT_READY')<div class="card border-warning"><div class="card-body"><h5>Actualizar a {{ $updateRun->to_version }}</h5><p>Se repetirá el preflight, se respaldarán los archivos afectados y sólo entonces se desplegará el código. Escriba <code>{{ $instance->slug }}</code> para confirmar.</p><form method="POST" action="{{ route('instances.update-runs.execute',[$instance,$updateRun]) }}" onsubmit="return confirm('¿Desplegar esta release en la instancia?')">@csrf<div class="input-group"><input class="form-control" name="confirmation" required autocomplete="off"><button class="btn btn-warning">Actualizar a {{ $updateRun->to_version }}</button></div></form></div></div>@endif
@if($updateRun->rollback_status)<div class="alert {{ $updateRun->rollback_status==='CODE_ROLLBACK_AVAILABLE'?'alert-warning':'alert-danger' }}">Rollback: {{ $updateRun->rollback_status }}. {{ $updateRun->database_review_required?'La base de datos requiere revisión manual.':'' }}</div>@endif
@endsection
