@extends('layouts/layoutMaster')
@section('title','Auditoría de actualización')
@section('content')
@include('admin.partials.flash')
@php $plan=$upgradeAudit->plan_json??[];$colors=['COMPATIBLE'=>'success','MANUAL_REVIEW'=>'warning','INCOMPATIBLE'=>'danger']; @endphp
<div class="d-flex justify-content-between mb-6"><div><h4>Dry-run · {{ $instance->name }}</h4><p>{{ $upgradeAudit->source_version }} → iKontrol {{ $upgradeAudit->target_version }}</p></div><span class="badge fs-6 bg-label-{{ $colors[$upgradeAudit->compatibility]??'secondary' }}">{{ $upgradeAudit->compatibility }}</span></div>
<div class="alert alert-info"><strong>Solo lectura:</strong> no ejecuta migraciones, SQL de cambio, comandos mutables ni reemplazo de archivos.</div>
<div class="row g-4 mb-6">@foreach(['DATABASE'=>'Base de datos','SETTINGS'=>'Settings','FILES'=>'Archivos','FISCAL'=>'Fiscal','ENVIRONMENT'=>'Entorno','FRAMEWORK'=>'Framework'] as $key=>$label)@php $summary=data_get($plan,"categories.$key",[]);$sev=$summary['severity']??'INFO'; @endphp<div class="col-md-6 col-xl-4"><div class="card h-100"><div class="card-header d-flex justify-content-between"><strong>{{ $label }}</strong><span class="badge bg-label-{{ $sev==='CRITICAL'?'danger':($sev==='WARNING'?'warning':'success') }}">{{ $sev==='INFO'?'READY':$sev }}</span></div><div class="card-body">{{ $summary['total']??0 }} verificaciones @foreach($summary['statuses']??[] as $status=>$count)<div>{{ $status }}: {{ $count }}</div>@endforeach</div></div></div>@endforeach</div>
<div class="card mb-6"><div class="card-header"><h5>Plan</h5></div><div class="card-body"><h6>Preservar</h6><ul>@foreach($plan['preserve']??[] as $value)<li>{{ $value }}</li>@endforeach</ul>@if($plan['fiscal_actions']??[])<h6>Fiscal</h6><ul>@foreach($plan['fiscal_actions'] as $value)<li>{{ $value }}</li>@endforeach</ul>@endif<h6>Riesgos</h6><ul>@forelse($plan['reasons']??[] as $value)<li>{{ $value }}</li>@empty<li>Sin conflictos críticos detectados.</li>@endforelse</ul><form method="POST" action="{{ route('instances.upgrade-audits.dry-run',[$instance,$upgradeAudit]) }}">@csrf<button class="btn btn-primary">Generar Dry-Run</button></form></div></div>
<div class="card"><div class="card-header"><h5>Evidencia</h5></div><div class="table-responsive"><table class="table"><thead><tr><th>Categoría</th><th>Objeto</th><th>Estado</th><th>Severidad</th><th>Actual</th><th>Esperado</th></tr></thead><tbody>@foreach($upgradeAudit->items as $item)<tr><td>{{ $item->category }}</td><td>{{ $item->object_name }}</td><td>{{ $item->status }}</td><td>{{ $item->severity }}</td><td class="text-break"><small>{{ $item->current_value }}</small></td><td class="text-break"><small>{{ $item->expected_value }}</small></td></tr>@endforeach</tbody></table></div></div>
@endsection
