<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;
use App\Models\{FactucareConversionPlan,IkontrolInstance};
use App\Services\AuditService;
use App\Services\LegacyFc2\FactucareConversionPlannerService;
use Illuminate\Http\Request;
class FactucareConversionController extends Controller {
 public function create(int $user,Request $request,FactucareConversionPlannerService $planner,AuditService $audit){$options=$this->validatedOptions($request);$result=$planner->plan($user,$options);$audit->record('factucare_conversion_plan_viewed','Vista previa de conversión FactuCare.','factucare_user',['legacy_user_id'=>$user,'rfc'=>$result['source']['rfc'],'destination_instance_id'=>$result['options']['destination_instance_id'],'status'=>$result['status'],'counts'=>$result['summary']]);return view('admin.legacy.factucare.conversion',compact('result')+['instances'=>IkontrolInstance::where('active',true)->orderBy('name')->get(),'plan'=>null,'sourceState'=>'SOURCE_UNSAVED']);}
 public function store(int $user,Request $request,FactucareConversionPlannerService $planner,AuditService $audit){$started=microtime(true);$result=$planner->plan($user,$this->validatedOptions($request));$plan=$planner->persist($result);$audit->record('factucare_conversion_plan_created','Plan de conversión FactuCare creado.',$plan,['legacy_user_id'=>$user,'rfc'=>$result['source']['rfc'],'destination_instance_id'=>$result['options']['destination_instance_id'],'status'=>$result['status'],'counts'=>$result['summary'],'duration_ms'=>(int)((microtime(true)-$started)*1000)]);return redirect()->route('legacy.factucare.conversion.plans.show',$plan)->with('success','Plan guardado. No se realizaron cambios en FC2 ni en iKontrol.');}
 public function show(FactucareConversionPlan $plan,FactucareConversionPlannerService $planner,AuditService $audit){$state=$planner->sourceState($plan);if($state==='SOURCE_CHANGED'&&$plan->status!=='STALE')$plan->update(['status'=>'STALE']);$plan->load('items','destination');$audit->record('factucare_conversion_plan_viewed','Plan de conversión FactuCare consultado.',$plan,['legacy_user_id'=>$plan->legacy_user_id,'rfc'=>$plan->legacy_rfc,'destination_instance_id'=>$plan->destination_instance_id,'status'=>$plan->status]);return view('admin.legacy.factucare.conversion_saved',compact('plan')+['sourceState'=>$state]);}
 public function regenerate(FactucareConversionPlan $plan,FactucareConversionPlannerService $planner,AuditService $audit){$started=microtime(true);$result=$planner->plan($plan->legacy_user_id,$plan->options_json);$planner->persist($result,$plan);$audit->record('factucare_conversion_plan_regenerated','Plan de conversión FactuCare regenerado.',$plan,['legacy_user_id'=>$plan->legacy_user_id,'rfc'=>$plan->legacy_rfc,'destination_instance_id'=>$plan->destination_instance_id,'status'=>$result['status'],'counts'=>$result['summary'],'duration_ms'=>(int)((microtime(true)-$started)*1000)]);return redirect()->route('legacy.factucare.conversion.plans.show',$plan)->with('success','Plan regenerado desde FC2 en modo de solo lectura.');}
 private function validatedOptions(Request $r):array{return $r->validate(['destination_instance_id'=>'nullable|integer|exists:ikontrol_instances,id','default_cfdi_use'=>'nullable|string|max:10|regex:/^[A-Z0-9]+$/','default_tax_object'=>'nullable|string|max:5|regex:/^[A-Z0-9]+$/','prepare_products'=>'nullable|boolean','apply_default_tax'=>'nullable|boolean','force_default_tax'=>'nullable|boolean','preserve_series'=>'nullable|boolean']);}
}