<?php
namespace App\Http\Controllers\Admin;
use App\Models\IkontrolInstance;use App\Services\{IkontrolStampService,InstanceComprehensiveDiagnosticService,InstanceLogService,InstanceRuntimeDiagnosticService};use Illuminate\Http\Request;use Illuminate\Validation\Rule;use Throwable;
class InstanceDiagnosticsController{
 public function stamps(Request$r,IkontrolInstance$instance,IkontrolStampService$s){$data=$r->validate(['action'=>['required',Rule::in(['credit','debit'])],'quantity'=>['required','integer','min:1','max:1000000'],'reason'=>['required','string','max:500']]);try{$s->move($instance,$data['action'],(int)$data['quantity'],$data['reason']);return redirect()->route('instances.show',[$instance,'tab'=>'stamps'])->with('success','Movimiento de timbres aplicado.');}catch(Throwable$e){return redirect()->route('instances.show',[$instance,'tab'=>'stamps'])->with('error',$e->getMessage());}}
 public function log(Request$r,IkontrolInstance$instance,string$file,InstanceLogService$s){try{return response()->json($s->read($instance,$file,(int)$r->integer('lines',100),$r->string('search')->toString()));}catch(Throwable$e){abort(404,$e->getMessage());}}
 public function clearLogs(IkontrolInstance$instance,InstanceLogService$s){try{$s->clear($instance);return redirect()->route('instances.show',[$instance,'tab'=>'logs'])->with('success','Logs limpiados.');}catch(Throwable$e){return redirect()->route('instances.show',[$instance,'tab'=>'logs'])->with('error',$e->getMessage());}}
 public function logCheck(IkontrolInstance$instance,InstanceRuntimeDiagnosticService$s){try{$result=$s->generateTestLog($instance);return redirect()->route('instances.show',[$instance,'tab'=>'logs'])->with('success','Prueba de logging completada.')->with('logging_check_result',$result);}catch(Throwable$e){return redirect()->route('instances.show',[$instance,'tab'=>'logs'])->with('error',$e->getMessage());}}
 public function diagnose(Request$r,IkontrolInstance$instance,string$type,InstanceRuntimeDiagnosticService$s){abort_unless(in_array($type,['admin','dashboard'],true),404);$data=$r->validate(['email'=>['required','email','max:255']]);try{$result=$type==='admin'?$s->diagnoseAdmin($instance,$data['email']):$s->diagnoseDashboard($instance,$data['email']);return redirect()->route('instances.show',[$instance,'tab'=>'operations'])->with('success','Diagnóstico completado.')->with('operation_result',$result);}catch(Throwable$e){return redirect()->route('instances.show',[$instance,'tab'=>'operations'])->with('error',$e->getMessage());}}
 public function comprehensive(Request$r,IkontrolInstance$instance,InstanceComprehensiveDiagnosticService$s){$data=$r->validate(['email'=>['nullable','email','max:255']]);try{$snapshot=$s->diagnose($instance,$data['email']??null);return redirect()->route('instances.show',[$instance,'tab'=>'diagnostic'])->with('success','Diagnóstico integral completado: '.$snapshot->status);}catch(Throwable$e){return redirect()->route('instances.show',[$instance,'tab'=>'diagnostic'])->with('error',$e->getMessage());}}
 public function installTools(IkontrolInstance$instance,InstanceComprehensiveDiagnosticService$s){try{$s->installTools($instance);return redirect()->route('instances.show',[$instance,'tab'=>'diagnostic'])->with('success','Herramientas de diagnóstico instaladas.');}catch(Throwable$e){return back()->with('error',$e->getMessage());}}
 public function repairWritable(IkontrolInstance$instance,InstanceComprehensiveDiagnosticService$s){try{$s->repairWritable($instance);return redirect()->route('instances.show',[$instance,'tab'=>'diagnostic'])->with('success','Permisos writable reparados.');}catch(Throwable$e){return back()->with('error',$e->getMessage());}}
}
