<?php
namespace App\Http\Controllers\Admin;
use App\Enums\InstallationStatus; use App\Http\Controllers\Controller; use App\Http\Requests\InstanceRequest; use App\Models\{Client,IkontrolInstance,IkontrolVersion,InstanceInstallationLog}; use App\Services\{AuditService,IkontrolInstanceConnectionService,IkontrolInstanceInspectorService,IkontrolStampService,InstanceLogService}; use Illuminate\Http\Request; use Throwable;
class InstanceController extends Controller{
 public function index(){return view('admin.instances.index',['instances'=>IkontrolInstance::with('client')->latest()->paginate(20)]);}
 public function create(){return view('admin.instances.register',['clients'=>Client::whereActive(true)->orderBy('name')->get(),'targetVersions'=>IkontrolVersion::whereActive(true)->orderByDesc('is_default')->orderByDesc('version')->get()]);}
 public function store(InstanceRequest$r,AuditService$a){$d=$r->validated();$path=$d['absolute_path']??rtrim(config('ikontrol.instances_root'),'/\\').DIRECTORY_SEPARATOR.$d['folder_name'];$host=$d['db_host']??config('ikontrol.db.host');$target=$d['target_version']??config('ikontrol.version_sources.default_target');unset($d['absolute_path'],$d['db_host'],$d['target_version']);$i=IkontrolInstance::create($d+['absolute_path'=>$path,'db_host'=>$host,'db_port'=>config('ikontrol.db.port'),'target_version'=>$target,'installation_origin'=>'EXISTING','upgrade_status'=>'NOT_AUDITED','installation_status'=>InstallationStatus::Ready,'active'=>true]);InstanceInstallationLog::create(['instance_id'=>$i->id,'step'=>'REGISTERING','status'=>'SUCCESS','message'=>'Instalación existente registrada manualmente.','created_at'=>now()]);$a->record('register_instance','Instalación existente registrada.',$i,['installation_origin'=>'EXISTING','target_version'=>$target]);return redirect()->route('instances.show',$i)->with('success','Instalación registrada sin modificar sus archivos ni su base de datos.');}
 public function show(IkontrolInstance$instance,Request$request,IkontrolStampService$stamps,InstanceLogService$logs,\App\Services\InstanceRuntimeDiagnosticService$diagnostics){$instance->load(['client','installationLogs','latestInspection','latestDiagnostic','template','latestUpgradeAudit']);$tab=$request->string('tab')->toString()?:'summary';$stampData=null;$logFiles=[];$recentErrors=[];$loggingStatus=null;try{if($tab==='stamps'&&$instance->template)$stampData=$stamps->status($instance);if($tab==='logs'&&$instance->template){$logFiles=$logs->listing($instance);$recentErrors=$logs->recentErrors($instance);$loggingStatus=$logs->filesystemStatus($instance)+$diagnostics->loggingStatus($instance);}}catch(Throwable$e){session()->flash('error',$e->getMessage());}return view('admin.instances.show',compact('instance','tab','stampData','logFiles','recentErrors','loggingStatus'));}
 public function testConnection(IkontrolInstance$instance,IkontrolInstanceConnectionService$s,AuditService$a){$r=$s->test($instance);$a->record('test_connection','Prueba de conexión ejecutada.',$instance,['success'=>$r['success']]);return back()->with($r['success']?'success':'error',$r['message']);}
 public function inspect(IkontrolInstance$instance,IkontrolInstanceInspectorService$inspector,AuditService$a){$r=$inspector->inspect($instance);$a->record('inspect_instance','Inspección de instancia ejecutada.',$instance,['success'=>$r['success'],'schema_status'=>$r['schema_status'],'duration_ms'=>$r['duration_ms']]);return back()->with($r['success']?'success':'error',$r['success']?'Información de la instancia actualizada.':'No fue posible inspeccionar la instancia.');}
}
